---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.
    filter.fluxcd.io/vscode: "regex:^3.[0-9]+-.*$"
spec:
  releaseName: home-assistant
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 2.5.0
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.117.5
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "rook-ceph-block"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - hass.eviljungle.com
      tls:
      - hosts:
        - hass.eviljungle.com
    service:
      type: LoadBalancer
      loadBalancerIP: 10.0.6.56
    hostNetwork: true
    tolerations:
    - key: "arm"
      operator: "Exists"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.5.0
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
        hosts:
        - hass-vscode.eviljungle.com
        tls:
        - hosts:
          - hass-vscode.eviljungle.com
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 2000Mi
    monitoring:
      enabled: false
    postgresql:
      enabled: true
      global:
        postgresql:
          postgresqlUsername: home-assistant
          postgresqlDatabase: home-assistant
      persistence:
        enabled: true
        storageClass: "rook-ceph-block"
  valueFileSecrets:
  - name: "home-assistant-helm-values"
