---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0.
    # filter.fluxcd.io/vscode: "regex:^2.[0-9]+-.*$"
spec:
  releaseName: home-assistant
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: home-assistant
    version: 0.10.0
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.105.5
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "rook-ceph-block"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    vscode:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 2000Mi
    monitoring:
      enabled: true
  valueFileSecrets:
  - name: "home-assistant-helm-values"
