---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0
spec:
  releaseName: home-assistant
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: home-assistant
    version: 0.9.8
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.100.1
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "rook-ceph-block"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 2.1600-vsc1.38.1
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
  valueFileSecrets:
  - name: "home-assistant-helm-values"
