apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: kube-system
spec:
  releaseName: vault
  rollback:
    enabled: true
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: v0.7.0
    path: .
  values:
    server:
      dataStorage:
        enabled: true
        storageClass: "rook-ceph-block"
      extraEnvironmentVars:
        GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-vault/account.json
      extraVolumes:
        - type: secret
          name: kms-vault
          path: /vault/userconfig
      tolerations: |
        - key: "arm"
          operator: "Exists"
      annotations:
        backup.velero.io/backup-volumes: data
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
      standalone:
        enabled: "false"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
      ha:
        enabled: "true"
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            seal "gcpckms" {
              project     = "kms-vault"
              region      = "global"
              key_ring    = "vault-unseal"
              crypto_key  = "vault-key"
            }
    ui:
      enabled: true
      serviceType: "ClusterIP"
  valueFileSecrets:
  - name: "vault-helm-values"