apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-ha
  namespace: kube-system
spec:
  releaseName: vault-ha
  helmVersion: v3
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: v0.3.1
    path: .
  values:
    server:
      extraSecretEnvironmentVars:
        - envName: VAULT_TOKEN
          secretName: vault
          secretKey: vault-unwrap-token
      tolerations: |
        - key: "arm"
          operator: "Exists"
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: nfs-client
      standalone:
        enabled: "false"
      ha:
        enabled: "true"
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "consul" {
            path = "vault"
            address = "HOST_IP:8500"
          }
          seal "transit" {
            address = "http://lb:8200"
            disable_renewal = "false"
            key_name = "autounseal"
            mount_path = "transit/"
            tls_skip_verify = "true"
          }
    # ui:
    #   enabled: true
