apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-raft
  namespace: kube-system
spec:
  releaseName: vault-raft
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: v0.5.0
    path: .
  values:
    server:
      extraEnvironmentVars:
        GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-vault/account.json
      extraVolumes:
        - type: secret
          name: kms-vault
          path: /vault/userconfig
      tolerations: |
        - key: "arm"
          operator: "Exists"
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
      standalone:
        enabled: "false"
      ha:
        enabled: "true"
        replicas: 3

        # Enables Vault's integrated Raft storage.  Unlike the typical HA modes where
        # Vault's persistence is external (such as Consul), enabling Raft mode will create
        # persistent volumes for Vault to store data according to the configuration under server.dataStorage.
        # The Vault cluster will coordinate leader elections and failovers internally.
        raft:

          # Enables Raft integrated storage
          enabled: true
          # Set the Node Raft ID to the name of the pod
          setNodeId: false
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            seal "gcpckms" {
              project     = "kms-vault"
              region      = "global"
              key_ring    = "vault-unseal"
              crypto_key  = "vault-key"
            }
    ui:
      # True if you want to create a Service entry for the Vault UI.
      #
      # serviceType can be used to control the type of service created. For
      # example, setting this to "LoadBalancer" will create an external load
      # balancer (for supported K8S installations) to access the UI.
      enabled: false
      serviceType: "ClusterIP"