---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/1Password/connect-helm-charts/main
  timeout: 3m
