---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: default
  annotations:
    flux.weave.works/ignore: "false"
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0
spec:
  releaseName: hass
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: home-assistant
    version: 0.9.4
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.97.1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: rbd
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 1.1156-vsc1.33.1
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          ingress.kubernetes.io/auth-type: "forward"
          ingress.kubernetes.io/auth-url: "http://auth0-forwardauth.kube-system.svc.cluster.local/authorize"
          ingress.kubernetes.io/auth-trust-headers: "true"
  valueFileSecrets:
  - name: "hass-values"
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hass-postgresql
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~11
spec:
  releaseName: hass-postgresql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: postgresql
    version: 6.2.0
  values:
    image:
      repository: bitnami/postgresql
      tag: 11.4.0-debian-9-r34
    postgresqlUsername: "homeassistant"
    postgresqlDatabase: "homeassistant"
    replication:
      enabled: true
      slaveReplicas: 2
      synchronousCommit: "on"
      numSynchronousReplicas: 1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: "rbd"
    metrics:
      enabled: true
  valueFileSecrets:
  - name: "hass-postgresql-values"
