---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mc
  namespace: default
  annotations:
    # flux.weave.works/automated: "true"
    # flux.weave.works/tag.chart-image: glob:latest
spec:
  releaseName: mc
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minecraft
    version: 0.3.2
  values:
    image: itzg/minecraft-server
    imageTag: latest
    persistence:
      storageClass: "rbd"
      dataDir:
        enabled: true
        Size: 10Gi
    # resources:
    #   requests:
    #     memory: 1024Mi
    minecraftServer:
      eula: "TRUE"
      version: "1.14.1"
      type: PAPER
      # spigotDownloadUrl: https://cdn.getbukkit.org/spigot/spigot-1.14.jar
      paperDownloadUrl: https://papermc.io/api/v1/paper/1.14.1/latest/download
      # jvmOpts: "-Xmx1024M -Xms1024M"
      difficulty: normal
      serviceType: LoadBalancer
      gameMode: creative
      ops: "83d9416e-216e-4ffb-81ae-d2bd455a398a"
      motd: "billimek minecraft server (creative)"
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mcsv
  namespace: default
  annotations:
    # flux.weave.works/automated: "true"
    # flux.weave.works/tag.chart-image: glob:latest
spec:
  releaseName: mcsv
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minecraft
    version: 0.3.2
  values:
    image: itzg/minecraft-server
    imageTag: latest
    persistence:
      storageClass: "rbd"
      dataDir:
        enabled: true
        Size: 10Gi
    # resources:
    #   requests:
    #     memory: 1024Mi
    minecraftServer:
      eula: "TRUE"
      version: "1.14.1"
      type: PAPER
      # spigotDownloadUrl: https://cdn.getbukkit.org/spigot/spigot-1.14.jar
      paperDownloadUrl: https://papermc.io/api/v1/paper/1.14.1/latest/download
      # jvmOpts: "-Xmx1024M -Xms1024M"
      difficulty: normal
      serviceType: LoadBalancer
      gameMode: survival
      ops: "83d9416e-216e-4ffb-81ae-d2bd455a398a"
      motd: "billimek minecraft server (survival)"
