---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'regexp:^(amd64-v2.*-r.*-.*)$'
spec:
  releaseName: nzbget
  chart:
    repository: https://billimek.github.io/helm-repo/
    name: nzbget
    version: 1.1.2
  values:
    image:
      repository: linuxserver/nzbget
      tag: amd64-v21.0-r2296-ls6
    service:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.153
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    timezone: "America/New_York"
    persistence:
      downloads:
        enabled: true
        existingClaim: nfs-media-pvc-10g
        subPath: Downloads
      config:
        enabled: true
        storageClass: "rbd"
        size: 30Gi
  valueFileSecrets:
  - name: "nzbget-values"
