---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:3.*-alpine
spec:
  releaseName: rabbitmq
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq-ha
    version: 1.19.0
  values:
    image:
      repository: rabbitmq
      tag: 3.7-alpine
    rabbitmqMQTTPlugin:
      enabled: true
    rabbitmqWebMQTTPlugin:
      enabled: true
    service:
      loadBalancerIP: ""
      type: LoadBalancer
    persistentVolume:
      enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
  valueFileSecrets:
  - name: "rabbitmq-values"
