---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'regexp:^(3\.[0-9]+\.[0-9]+-alpine)$'
spec:
  releaseName: rabbitmq
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq-ha
    version: 1.25.0
  values:
    image:
      repository: rabbitmq
      tag: 3.7.12-alpine
    rabbitmqMQTTPlugin:
      enabled: true
    rabbitmqWebMQTTPlugin:
      enabled: true
    service:
      clusterIP: ""
      loadBalancerIP: "10.2.0.102"
      type: LoadBalancer
    persistentVolume:
      enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    rabbitmqErlangCookie: "9uVNsf2plnpyslPjqUVaDmGTUml2wJlb"
  valueFileSecrets:
  - name: "rabbitmq-values"
