---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'glob:amd64-v0.*.*.*'
spec:
  releaseName: radarr
  chart:
    repository: https://billimek.com/billimek-charts/
    name: radarr
    version: 2.0.3
  values:
    image:
      repository: linuxserver/radarr
      tag: 'amd64-v0.2.0.1344-ls16'
      pullPolicy: Always
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    timezone: "America/New_York"
    persistence:
      config:
        enabled: true
        storageClass: "rbd"
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc-10g
        accessMode: ReadWriteMany
      movies:
        enabled: true
        existingClaim: nfs-media-pvc-10g
        subPath: Videos
        accessMode: ReadWriteMany
  valueFileSecrets:
  - name: "radarr-values"
