---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rutorrent
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:amd64-*
spec:
  releaseName: rutorrent
  chart:
    repository: https://billimek.github.io/helm-repo/
    name: rutorrent
    version: 1.0.0
  values:
    image:
      repository: linuxserver/rutorrent
      tag: amd64-4d3029cf-ls8
    btService:
      type: LoadBalancer
      port: 51413
      loadBalancerIP: 10.2.0.155
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        ingress.kubernetes.io/auth-type: "basic"
        ingress.kubernetes.io/auth-secret: "traefik-basic-auth-jeff"
    timezone: "America/New_York"
    persistence:
      downloads:
        enabled: true
        existingClaim: nfs-media-pvc-10g
        subPath: Downloads
  valueFileSecrets:
  - name: "rutorrent-values"