---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'glob:amd64-2.*.*.*'
spec:
  releaseName: sonarr
  chart:
    repository: https://billimek.com/billimek-charts/
    name: sonarr
    version: 2.0.6
  values:
    image:
      repository: linuxserver/sonarr
      tag: 'amd64-2.0.0.5337-ls74'
      pullPolicy: Always
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    timezone: "America/New_York"
    persistence:
      config:
        enabled: true
        storageClass: "rbd"
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc-10g
        accessMode: ReadWriteMany
      tv:
        enabled: true
        existingClaim: nfs-media-pvc-10g
        subPath: Videos
        accessMode: ReadWriteMany
  valueFileSecrets:
  - name: "sonarr-values"
