---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'regexp:^(5\.[0-9][0-9]\.[0-9]+)$'
spec:
  releaseName: unifi
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: unifi
    version: 0.4.2
  values:
    image:
      repository: jacobalberty/unifi
      tag: 5.10.26
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 20Gi
      storageClass: rbd
    timezone: "America/New_York"
    runAsRoot: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.156
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.157
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.158
    podAnnotations:
      backup.velero.io/backup-volumes: unifi-data
  valueFileSecrets:
  - name: "unifi-values"
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp:
  name: unifi-backup
  namespace: velero
spec:
  schedule: 0 6 * * *
  template:
    includedNamespaces:
    - '*'
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: unifi
    ttl: 168h0m0s
status:
  lastBackup:
  phase: ""
  validationErrors:
