apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
  name: vernemq-old
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.2.0.102
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  selector:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
  sessionAffinity: None
  type: LoadBalancer
