apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.4
spec:
  releaseName: nfs-client-provisioner
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-client-provisioner
    version: 1.2.1
  values:
    image:
      repository: quay.io/external_storage/nfs-client-provisioner
      tag: v3.1.0-k8s1.11
    nfs:
      server: "10.0.10.7"
      path: "/tank/data/k8s-nfs"
