  
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"	
    fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: kured
  chart:
    repository: https://weaveworks.github.io/kured
    name: kured	
    version: 2.0.3
  values:
    image:
      repository: raspbernetes/kured
      tag: 1.4.4
    configuration:
      startTime: "1:00"
      endTime: "6:00"
      timeZone: "America/New_York"
    tolerations:	
    - key: "arm"	
      operator: "Exists"	
    metrics:
      create: true
  valueFileSecrets:	
  - name: "kured-helm-values"
