---	
apiVersion: helm.fluxcd.io/v1	
kind: HelmRelease	
metadata:	
  name: kured	
  namespace: kube-system	
  annotations:	
    fluxcd.io/automated: "true"	
    fluxcd.io/tag.chart-image: semver:~1	
spec:	
  releaseName: kured	
  chart:	
    repository: https://kubernetes-charts.storage.googleapis.com/	
    name: kured	
    version: 1.5.01
  values:	
    image:	
      repository: raspbernetes/kured	
      tag: 1.4.0	
    tolerations:	
    - key: "arm"	
      operator: "Exists"	
    extraArgs:
      start-time: 2am
      end-time: 9am
      time-zone: "America/New_York"
  valueFileSecrets:	
  - name: "kured-helm-values"
