---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~1.
    fluxcd.io/tag.postgresql: semver:~11
spec:
  releaseName: teslamate
  helmVersion: v3
  chart:
    repository: https://billimek.com/billimek-charts/
    name: teslamate
    version: 2.0.3
  values:
    image:
      repository: teslamate/teslamate
      tag: 1.18.2
    timeZone: "America/New_York"
    mqtt:
      enabled: true
      host: vernemq
      username: mqtt
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
    postgresql:
      image:
        repository: postgres
        tag: '11.7'
      persistence:
        enabled: true
        storageClass: nfs-client
      shmVolume:
        enabled: false
      volumePermissions:
        enabled: false
      master:
        tolerations:
        - key: "arm"
          operator: "Exists"
  valueFileSecrets:
  - name: "teslamate-helm-values"
