---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~1.
    fluxcd.io/tag.postgresql: semver:~11
spec:
  releaseName: teslamate
  chart:
    repository: https://k8s-at-home.com/charts/
    name: teslamate
    version: 3.0.1
  values:
    image:
      repository: teslamate/teslamate
      tag: 1.20.0
    timeZone: "America/New_York"
    mqtt:
      enabled: true
      host: vernemq
      username: mqtt
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
    probes:
      liveness:
        failureThreshold: 15
        periodSeconds: 10
      readiness:
        failureThreshold: 15
        periodSeconds: 10
      startup:
        initialDelaySeconds: 15
        failureThreshold: 30
        periodSeconds: 10
    postgresql:
      image:
        repository: postgres
        tag: '11.7'
      persistence:
        enabled: true
        storageClass: rook-ceph-block
      shmVolume:
        enabled: false
      volumePermissions:
        enabled: false
      master:
        tolerations:
        - key: "arm"
          operator: "Exists"
        podAnnotations:
          backup.velero.io/backup-volumes: data
  valueFileSecrets:
  - name: "teslamate-helm-values"
