---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1.
    fluxcd.io/tag.postgresql: semver:~12
spec:
  releaseName: teslamate
  chart:
    repository: https://billimek.com/billimek-charts/
    name: teslamate
    version: 1.0.0
  values:
    image:
      repository: teslamate/teslamate
      tag: 1.13.2
    timeZone: "America/New_York"
    mqtt:
      enabled: true
      host: rabbitmq-ha
      username: mqtt
      password: mqtt
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
    tolerations:
    - key: "arm"
      operator: "Exists"
    postgresql:
      image:
        repository: postgres
        tag: 12.1
      persistence:
        enabled: true
        storageClass: nfs-client
      shmVolume:
        enabled: false
      volumePermissions:
        enabled: false
      master:
        tolerations:
        - key: "arm"
          operator: "Exists"
  valueFileSecrets:
  - name: "teslamate-helm-values"
