---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: rook-ceph
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: v1.5.0
  values:
    csi:
      kubeletDirPath: /var/lib/kubelet
      cephcsi:
        image: quay.io/cephcsi/cephcsi:v3.1.1
      registrar:
        image: raspbernetes/csi-node-driver-registrar:2.0.1
      provisioner:
        image: raspbernetes/csi-external-provisioner:2.0.0
      snapshotter:
        image: raspbernetes/csi-external-snapshotter:3.0.0
      attacher:
        image: raspbernetes/csi-external-attacher:3.0.0
      resizer:
        image: raspbernetes/csi-external-resizer:1.0.0
      pluginTolerations:
        - key: "arm"
          operator: "Exists"
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
