---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.grafana: semver:~6
    # flux.weave.works/tag.alertmanager.alertmanagerSpec: semver:~0
    # flux.weave.works/tag.alertmanager.alertmanagerSpec: glob:v0.16.*
    # flux.weave.works/tag.prometheus.prometheusSpec: glob:v2.*.*
    # flux.weave.works/tag.prometheusOperator: glob:v0.*.*
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 5.15.0
  values:
    alertmanager:
      alertmanagerSpec:
#        image:
#          repository: quay.io/prometheus/alertmanager
#          tag: v0.16.2
        logFormat: logfmt
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: rbd
              resources:
                requests:
                  storage: 10Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          ingress.kubernetes.io/auth-type: "forward"
          ingress.kubernetes.io/auth-url: "http://auth0-forwardauth.kube-system.svc.cluster.local/authorize"
          ingress.kubernetes.io/auth-trust-headers: "true"
    grafana:
      image:
        repository: grafana/grafana
        tag: 6.2.5
      deploymentStrategy: Recreate
      persistence:
        enabled: true
        storageClassName: "rbd"
        accessModes:
        - ReadWriteOnce
        size: 10Gi
      env:
        GF_EXPLORE_ENABLED: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
      additionalDataSources:
      - name: loki
        type: loki
        access: proxy
        url: http://loki.logs.svc.cluster.local:3100
      - name: influxdb
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: telegraf
      - name: cable_modem_stats
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: cable_modem_stats
      - name: comcast
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: comcast
      - name: home_assistant
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: home_assistant
      - name: speedtests
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: speedtests
      - name: uptimerobot
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: uptimerobot
      grafana.ini:
        paths:
          data: /var/lib/grafana/data
          logs: /var/log/grafana
          plugins: /var/lib/grafana/plugins
          provisioning: /etc/grafana/provisioning
        analytics:
          check_for_updates: true
        log:
          mode: console
        grafana_net:
          url: https://grafana.net
    coreDns:
      enabled: false
    kubeDns:
      enabled: true
    kubeEtcd:
      enabled: true
      endpoints:
      - 10.2.0.10
      - 10.2.0.11
      - 10.2.0.12
      service:
        port: 2379
        targetPort: 2379
    prometheus-node-exporter:
      tolerations:
      - key: "node-role.kubernetes.io/etcd"
        operator: "Exists"
      - key: "node-role.kubernetes.io/controlplane"
        operator: "Exists"
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          ingress.kubernetes.io/auth-type: "forward"
          ingress.kubernetes.io/auth-url: "http://auth0-forwardauth.kube-system.svc.cluster.local/authorize"
          ingress.kubernetes.io/auth-trust-headers: "true"
      prometheusSpec:
#        image:
#          repository: quay.io/prometheus/prometheus
#          tag: v2.9.1
        retention: 90d
        enableAdminAPI: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: rbd
              resources:
                requests:
                  storage: 50Gi
        additionalScrapeConfigs:
        - job_name: 'netdata-scrape'
          metrics_path: '/api/v1/allmetrics'
          params:
              # format: prometheus | prometheus_all_hosts
              # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP 
            format: [prometheus]
          honor_labels: true
          static_configs:
          - targets:
            - proxmox:19999
            - proxmox-b:19999
            - proxmox-c:19999
            - lb:19999
            - pihole:19999
            - k8s-master-a:19999
            - k8s-master-b:19999
            - k8s-master-c:19999
            - k8s-1:19999
            - k8s-2:19999
            - k8s-3:19999
            - k8s-4:19999
        - job_name: 'stash-scrape'
          metrics_path: '/metrics'
          params:
            format: [prometheus]
          honor_labels: true
          static_configs:
          - targets:
            - stash.kube-system:56789
        - job_name: 'wmi-exporter-scrape'
          metrics_path: '/metrics'
          params:
            format: [prometheus]
          honor_labels: true
          static_configs:
          - targets:
            - nvr:9182
  valueFileSecrets:
  - name: "prometheus-operator-values"
