apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesla-dashcam
  labels:
    app: tesla-dashcam
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tesla-dashcam
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: tesla-dashcam
    spec:
      containers:
      - name: tesla-dashcam
        env:
        - name: TZ
          value: America/New_York
        image: billimek/tesla_dashcam:1.0.0
        args: ["--delete_source", "--skip_existing", "--monitor", "--monitor_trigger", "ARCHIVE_UPLOADED", "--motion_only", "--output", "/output", "/input/SentryClips", "/input/SavedClips"]
        volumeMounts:
        - mountPath: /input
          name: media
          subPath: Videos/Tesla/
        - mountPath: /output
          name: media
          subPath: Videos/tesla_dashcam/
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: nfs-media-pvc