apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: network-services
    metallb.universe.tf/allow-shared-ip: blocky-svc-old
  labels:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
  name: blocky-udp-old
  namespace: default
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 10.2.0.160
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
  sessionAffinity: None
  type: LoadBalancer
