---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+)$'
spec:
  releaseName: influxdb
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: influxdb
    version: 1.4.1
  values:
    image:
      repository: "influxdb"
      tag: "1.7.8"
    service:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.151
    persistence:
      enabled: true
      size: 50Gi
      storageClass: nfs-client
    resources:
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 4Gi
        # cpu: 4
    livenessProbe:
      timeoutSeconds: 10
    livenessProbe:
      readinessProbe: 10
    config:
      opentsdb:
        enabled: true
    podAnnotations:
      backup.velero.io/backup-volumes: data
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
