---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://raw.githubusercontent.com/1Password/connect-helm-charts/main
      chart: connect
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
      interval: 5m
  values:
    namespace: kube-system
    operator:
      create: true
      autoRestart: true
      pollingInterval: 10
      watchNamespace:
      - "default"
      serviceAccount:
        create: true
      roleBinding:
        create: true
      clusterRole:
        create: true
    service:
      type: ClusterIP
      port: 8080
  valuesFrom:
  - kind: Secret
    name: "1password-helm-values"
    targetPath: "connect.credentials"
    optional: false
