---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: blocky
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^v([0-9]+\.[0-9]+)$'
spec:
  releaseName: blocky
  helmVersion: v3
  resetValues: true
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: blocky
    version: 4.0.0
  values:
    image:
      repository: spx01/blocky
      tag: v0.10
    replicas: 3
    timeZone: "America/New_York"
    config:
      upstream:
        externalResolvers:
        - udp:8.8.8.8
        - udp:8.8.4.4
        - udp:1.1.1.1
        - tcp-tls:1.0.0.1:853
        - https://cloudflare-dns.com/dns-query
      conditional:
        mapping:
          local: udp:10.0.7.1
          status.eviljungle.com: udp:1.1.1.1
          cloud.eviljungle.com: udp:8.8.8.8
          eviljungle.com: udp:10.0.7.1
      customDNS:
          mapping:
            # eviljungle.com: 10.0.7.1
            mcsv.eviljungle.com: 10.0.6.102
            mcsv-br.eviljungle.com: 10.0.6.104
            skyblock.eviljungle.com: 10.0.6.105
            nas: 10.0.7.11
            proxmox: 10.0.7.7
            proxmox-b: 10.0.7.9
            proxmox-c: 10.0.7.14
            k3s-0: 10.2.0.30
            whitebridge: 10.0.7.1
            unifi: 10.0.6.55
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - https://mirror1.malwaredomains.com/files/justdomains
          - http://sysctl.org/cameleon/hosts
          - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          kids:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
          none:
          - nil
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/white.list
        clientGroupsBlock:
          default:
            - none
          10.0.2.1/24:
            - ads
          *nsley*:
            - ads
            - kids
          *rinley*:
            - ads
            - kids
      clientLookup:
        upstream: udp:10.0.7.1
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    probes:
      liveness:
        failureThreshold: 5
        periodSeconds: 10
      readiness:
        failureThreshold: 5
        periodSeconds: 10
      startup:
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10
    serviceTCP:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 10.0.6.100
      annotations:
        metallb.universe.tf/allow-shared-ip: blocky
    serviceUDP:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 10.0.6.100
      annotations:
        metallb.universe.tf/allow-shared-ip: blocky
    serviceMonitor:
      enabled: true
    tolerations:
    - key: "arm"
      operator: "Exists"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 280Mi
        cpu: 50m
      limits:
        memory: 1000Mi
