apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0.7
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io/
    name: cert-manager
    version: v0.7.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v0.7.0
    extraArgs: 
      - --dns01-self-check-nameservers "8.8.8.8:53,1.1.1.1:53"
