apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: consul
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: consul
    version: 3.5.0
  values:
    ImageTag: "1.0.0"
    Image: consul
    StorageClass: "rbd"
    uiIngress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        ingress.kubernetes.io/auth-type: "forward"
        ingress.kubernetes.io/auth-url: "http://auth0-forwardauth.kube-system.svc.cluster.local/authorize"
        ingress.kubernetes.io/auth-trust-headers: "true"
  valueFileSecrets:
  - name: "consul-values"
