---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
  namespace: flux
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3032
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxcloud
  namespace: flux
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
      - name: fluxcloud
        image: billimek/fluxcloud:debug
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3032
        env:
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              name: fluxcloud
              key: slack_url
        - name: SLACK_CHANNEL
          value: "#notifications"
        # Or configure multiple channels
        # (comma separated <channel>=<namespace>) string:
        #  value: "#kubernetes=*,#team=team"
        - name: SLACK_USERNAME
          value: Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: ":heart:"
        - name: GITHUB_URL
          value: "https://github.com/billimek/k8s-gitops/"
        - name: LISTEN_ADDRESS
          value: ":3032"
        - name: TITLE_TEMPLATE
          value: |2-
            {{ if eq .EventType "commit" }}Applying changes from commit{{ end }}
            {{ if eq .EventType "autorelease" }}Auto releasing resources{{ end }}
        - name: BODY_TEMPLATE
          value: >2-
            {{ if or (eq .EventType "autorelease") (eq .EventType "commit") }}
            {{ range $resourceName, $resourceResult := .EventResult }}
            {{ if eq $resourceResult.Status "success" }}
            {{ range $resourceResult.PerContainer }}
            {{ if not (eq .Current.String .Target.String) }}
            * Updating *{{ replace $resourceName.String ":fluxhelmrelease" "" }}* to *{{ .Current.Tag }}*

            {{ end }}
            {{ end }}
            {{ end }}
            {{ if eq $resourceResult.Status "error" }}
            *Error updating {{ replace $resourceName.String ":fluxhelmrelease" "" }}*

            *Error message*: {{ $resourceResult.Error }}
            {{ end }}
            {{ end }}
            {{ end }}
