apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: auth0
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: latest
spec:
  releaseName: auth0
  chart:
    repository: https://billimek.github.io/helm-repo/
    name: forwardauth
    version: 0.1.0
  values:
    image:
      tag: latest
      repository: index.docker.io/dniel/forwardauth
    replicaCount: 1
    logLevel: PRODUCTION
  valueFileSecrets:
  - name: "forwardauth-values"