---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    flux.weave.works/ignore: "false"
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: 1.66.0
  values:
    image: traefik
    imageTag: 1.7.10
    serviceType: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 10.2.0.150
    replicas: 1
    startupArguments:
    - --ping
    debug:
      enabled: true
    rbac:
      enabled: true
    ssl:
      enabled: true
      enforced: false
      insecureSkipVerify: true
      upstream: true
    # kvprovider:
    #   storeAcme: true
    #   consul:
    #     endpoint: consul:8500
    #     watch: true
    #     prefix: traefik
    # acme:
    #   enabled: false
    #   staging: false
    #   logging: true
    #   domains:
    #     enabled: true
    #   challengeType: dns-01
    #   dnsProvider:
    #     name: cloudflare
    #   delayBeforeCheck: 120
    #   resolvers:
    #   - 1.1.1.1:53
    #   - 8.8.8.8:53
    #   persistence:
    #     enabled: false
    dashboard:
      enabled: false
      statistics:
        recentErrors: 25
    deployment:
      hostPort:
        dashboardEnabled: false
  valueFileSecrets:
  - name: "traefik-values"
