apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/ignore: "true"
spec:
  releaseName: openebs
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: openebs
    version: 0.8.1
  values:
    apiserver:
      image: "quay.io/openebs/m-apiserver"
      imageTag: "0.8.0"
    provisioner:
      image: "quay.io/openebs/openebs-k8s-provisioner"
      imageTag: "0.8.0"
    snapshotOperator:
      controller:
        image: "quay.io/openebs/snapshot-controller"
        imageTag: "0.8.0"
      provisioner:
        image: "quay.io/openebs/snapshot-provisioner"
        imageTag: "0.8.0"
    ndm:
      image: "quay.io/openebs/node-disk-manager-amd64"
      imageTag: "v0.2.0"
      sparse:
        enabled: "false"
    jiva:
      image: "quay.io/openebs/jiva"
      imageTag: "0.8.0"
    cstor:
      pool:
        image: "quay.io/openebs/cstor-pool"
        imageTag: "0.8.0"
      poolMgmt:
        image: "quay.io/openebs/cstor-pool-mgmt"
        imageTag: "0.8.0"
      target:
        image: "quay.io/openebs/cstor-istgt"
        imageTag: "0.8.0"
      volumeMgmt:
        image: "quay.io/openebs/cstor-volume-mgmt"
        imageTag: "0.8.0"
    policies:
      monitoring:
        enabled: true
        image: "quay.io/openebs/m-exporter"
        imageTag: "0.8.0"