apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:RELEASE..*
spec:
  releaseName: minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 2.4.13
  values:
    image:
      repository: minio/minio
      tag: RELEASE.2019-04-09T01-22-30Z
    persistence:
      existingClaim: "nfs-data-pvc-10g"
      subPath: "minio"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
  valueFileSecrets:
  - name: "minio-values"