---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: lazylibrarian
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:0.9.*
spec:
  releaseName: lazylibrarian
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: lazylibrarian
    version: 2.0.1
  values:
    image:
      repository: linuxserver/lazylibrarian
      tag: e3508ffb-ls3

    timezone: "America/New_York"
    puid: 1001
    pgid: 1001

    # Linuxserver.io additional layers.
    # Enables additional features for the image, at the cost of increased size and
    # possible incompatabilities with certain architectures. Disabled by default.
    #
    # To enable, set enabled to true, and follow the guide at: https://github.com/linuxserver/docker-lazylibrarian#application-setup
    # to configure the application.
    dockerMods:
      # Enable the Calibre Docker Mod to allow Calibredb import
      calibre:
        enabled: true
        image:
          repository: linuxserver/calibre-web
          tag: calibre
      # Enable the FFMpeg Docker Mod. This allows using the audiobook conversion features of LazyLibrarian.
      ffmpeg:
        enabled: true
        image:
          repository: linuxserver/mods
          tag: lazylibrarian-ffmpeg
    podAnnotations:
      backup.velero.io/backup-volumes: config

    persistence:
      enabled: true
      annotations: {}
      storageClass: "rook-ceph-block"
      size: 5Gi

      # Any extra volumes to define for the pod
      # Volumes will be mounted to the folder specified under mountPath
      # If no mountPath is set it will be mounted to /mnt/<name>
      extraVolumes:
      - name: media
        persistentVolumeClaim:
          claimName: nfs-media-downloads-pvc
        mountPath: "/mnt/media"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
      hosts:
      - host: ll.eviljungle.com
        paths:
        - "/"
      tls:
      - hosts:
        - "ll.eviljungle.com"


    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    probes:
      liveness:
        enabled: true
        scheme: HTTP
        initialDelaySeconds: 60
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        enabled: true
        scheme: HTTP
        initialDelaySeconds: 60
        failureThreshold: 5
        timeoutSeconds: 10
      startup:
        enabled: true
        scheme: HTTP
        failureThreshold: 30
        periodSeconds: 10

    # tolerations: []
