---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mcsv
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(1\.[0-9]+\.[0-9]+-adopt13)$
spec:
  releaseName: mcsv
  rollback:
    enable: true
  chart:
    repository: https://itzg.github.io/minecraft-server-charts/
    name: minecraft
    version: 2.0.7
  values:
    image: itzg/minecraft-server
    imageTag: 1.8.0-adopt13
    persistence:
      storageClass: "rook-ceph-block"
      dataDir:
        enabled: true
        Size: 10Gi
    resources:
      requests:
        memory: 1500Mi
        cpu: 250m
      limits:
        memory: 2001Mi
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    extraEnv:
      ENABLE_AUTOPAUSE: TRUE
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: PAPER
      paperDownloadUrl: https://papermc.io/api/v1/paper/1.16.3/latest/download
      forceReDownload: true
      jvmOpts: "-Xmx1024M -Xms1024M  -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs"
      difficulty: normal
      maxTickTime: -1
      serviceType: LoadBalancer
      gameMode: survival
      motd: "\u00a7feviljungle\u00a7: (\u00a7e\u00a7lsurvival\nl - \u00a7c\u00a7lHARDCORE\u00a7)"
      icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-23.png
      loadBalancerIP: 10.0.6.102
      rcon:
        enabled: true
        port: 25575
        password: "mc-rcon"
        serviceType: LoadBalancer