---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mc-test
  namespace: default
  labels:
    app: mc-test-minecraft
spec:
  releaseName: mc-test
  rollback:
    enable: true
  chart:
    repository: https://itzg.github.io/minecraft-server-charts/
    name: minecraft
    version: 2.0.2
  values:
    image: itzg/minecraft-server
    imageTag: adopt13
    persistence:
      storageClass: "rook-cephfs"
      dataDir:
        enabled: true
        Size: 10Gi
    resources:
      requests:
        memory: 1500Mi
        cpu: 250m
      limits:
        memory: 2000Mi
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 5
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 5
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: PAPER
      paperDownloadUrl: https://papermc.io/api/v1/paper/1.16.1/latest/download
      forceReDownload: true
      jvmOpts: "-Xmx1024M -Xms1024M  -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs"
      difficulty: normal
      serviceType: LoadBalancer
      gameMode: creative
      motd: "TEST minecraft server (creative)"
      loadBalancerIP: 10.0.6.105
