---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mc-br
  namespace: default
spec:
  releaseName: mc-br
  rollback:
    enable: true
  chart:
    repository: https://itzg.github.io/minecraft-server-charts/
    name: minecraft-bedrock
    version: 1.0.0
  values:
    # image: itzg/minecraft-bedrock-server
    # imageTag: latest
    persistence:
      storageClass: "rook-ceph-block"
      dataDir:
        enabled: true
        Size: 10Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1000Mi
    # livenessProbe:
    #   initialDelaySeconds: 30
    # readinessProbe:
    #   initialDelaySeconds: 30
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      difficulty: normal
      gameMode: creative
      levelName: world
      serverName: "(creative) billimek minecraft"
      serviceType: LoadBalancer
      loadBalancerIP: 10.0.6.103
