---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-lobby
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/minecraft-server
    imageTag: 2021.15.0-java16
    persistence:
      storageClass: "rook-ceph-block"
      dataDir:
        enabled: true
        Size: 5Gi
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    extraEnv:
      ENABLE_AUTOPAUSE: TRUE
      SPIGET_RESOURCES: "6245,91347"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: PAPER
      paperDownloadUrl: https://papermc.io/api/v1/paper/1.17.1/latest/download
      forceReDownload: true
      onlineMode: false
      difficulty: peaceful
      maxTickTime: -1
      serviceType: ClusterIP
      gameMode: adventure
      motd: "\u00a7feviljungle\u00a7 - \u00a7a\u00a7llobby\u00a7"
      icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-13.png
      rcon:
        enabled: false
