apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: velero
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: velero
    version: 1.0.0
  values:
    image:
      repository: gcr.io/heptio-images/velero
      tag: v1.0.0
    metrics:
      enabled: true
    configuration:
      provider: aws
      backupStorageLocation:
        name: aws
        bucket: velero
    deployRestic: true
    restic:
      podVolumePath: /opt/rke/var/lib/kubelet/pods
      privileged: false
    schedules:
      daily-backup:
        schedule: "0 0 * * *"
        template:
          ttl: "240h"
  valueFileSecrets:
  - name: "velero-values"
