apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: kube-system
spec:
  releaseName: longhorn
  chart:
    git: https://github.com/longhorn/longhorn.git
    ref: master
    path: chart
  values:
    service:
      ui:
        type: ClusterIP
    ingress:
      enabled: true
      tls: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    persistence:
      defaultClass: false
    csi:
      kubeletRootDir: /var/lib/kubelet
  valueFileSecrets:
  - name: "longhorn-helm-values"
