apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph-system
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/ignore: "false"
spec:
  releaseName: rook-ceph
  chart:
    repository: https://charts.rook.io/alpha
    name: rook-ceph
    version: v0.9.1
  values:
    agent:
      flexVolumeDirPath: "/var/lib/kubelet/volumeplugins"
      toleration: NoSchedule
      tolerationKey: node-role.kubernetes.io/controlplane
    discover:
      toleration: NoSchedule
      tolerationKey: node-role.kubernetes.io/controlplane
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: "true"
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: "true"