---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valheim
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: valheim
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: lloesche/valheim-server
      tag: latest
    env:
      SERVER_NAME: Billimek's Kubernetes Valheim
      WORLD_NAME: billimek
      SERVER_PUBLIC: true
      SUPERVISOR_HTTP: true
      STATUS_HTTP: true
      TZ: America/New_York
      # DNS_1: 8.8.8.8
      # DNS_2: 8.8.4.4
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: "rook-ceph-block"
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      loadBalancerIP: 10.0.6.58
      annotations:
        metallb.universe.tf/allow-shared-ip: valheim
      additionalServices:
        - enabled: true
          nameSuffix: supervisor
          type: LoadBalancer
          loadBalancerIP: 10.0.6.58
          port:
            port: 9001
            name: supervisor
            protocol: TCP
            targetPort: supervisor
          annotations:
            metallb.universe.tf/allow-shared-ip: valheim
          additionalPorts:
          - name: status
            port: 80
            protocol: TCP
            targetPort: 80
    resources:
      requests:
        memory: 4096Mi
        cpu: 250m
      limits:
        memory: 5120Mi
    podAnnotations:
      backup.velero.io/backup-volumes: config
  valuesFrom:
  - kind: Secret
    name: "valheim-helm-values"
    optional: false
