---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(5\.[0-9][0-9]\.[0-9]+)$'
spec:
  releaseName: unifi
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: unifi
    version: 0.5.2
  values:
    image:
      repository: jacobalberty/unifi
      tag: 5.12.35
    persistence:
      enabled: true
      size: 20Gi
      storageClass: rook-ceph-block
    timezone: "America/New_York"
    runAsRoot: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    guiService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.156
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-tcp
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.156
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-tcp
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.156
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-udp
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.156
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-udp
    podAnnotations:
      backup.velero.io/backup-volumes: unifi-data
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
  valueFileSecrets:
  - name: "unifi-helm-values"
