---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: radarr
    version: 4.1.1
  values:
    image:
      repository: linuxserver/radarr
      tag: 3.0.0.3049-ls10
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 3Gi
      downloads:
        enabled: false
      movies:
        enabled: false
      extraExistingClaimMounts:
        - name: media
          existingClaim: nfs-media-pvc
          mountPath: /media
          readOnly: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    tolerations:
    - key: "arm"
      operator: "Exists"
  valueFileSecrets:
  - name: "radarr-helm-values"
