apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-elasticsearch-data
  namespace: logs
spec:
  selector:
    matchLabels:
      app: elasticsearch-data
      component: data
  fileGroups:
  - path: /usr/share/elasticsearch/data
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv-10g-logs
    storageSecretName: restic-secret
  schedule: '0 0 7 * * *'
  spec.paused: true
  volumeMounts:
  - mountPath: /usr/share/elasticsearch/data
    name: data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
---
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-elasticsearch-master
  namespace: logs
spec:
  selector:
    matchLabels:
      app: elasticsearch-master
  fileGroups:
  - path: /usr/share/elasticsearch/data
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv-10g-logs
    storageSecretName: restic-secret
  schedule: '0 30 7 * * *'
  spec.paused: true
  volumeMounts:
  - mountPath: /usr/share/elasticsearch/data
    name: data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true