apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-rabbitmq
  namespace: default
spec:
  selector:
    matchLabels:
      app: rabbitmq-ha
  fileGroups:
  - path: /var/lib/rabbitmq
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv-10g
    storageSecretName: restic-secret
  schedule: '0 0 12 * * *'
  volumeMounts:
  - mountPath: /var/lib/rabbitmq
    name: data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
