apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-rtorrent-flood
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: rtorrent-flood
  fileGroups:
  - path: /flood-db
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv-10g
    storageSecretName: restic-secret
  schedule: '0 0 15 * * *'
  volumeMounts:
  - mountPath: /flood-db
    name: flood-db
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
