---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ser2sock
  namespace: default
spec:
  releaseName: ser2sock
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: ser2sock
    version: 1.0.2
  values:
    image:
      repository: tenstartups/ser2sock
      tag: armhf
      imagePullPolicy: Always
    timezone: "America/New York"
    device: "/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00DPTS-if00-port0"
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 50Mi
        cpu: 15m
      limits:
        memory: 250Mi
        hostdev.k8s.io/dev_serial_by-id_usb-FTDI_FT230X_Basic_UART_DO00DPTS-if00-port0: 1
