---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ser2sock
  namespace: default
spec:
  releaseName: ser2sock
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: ser2sock
    version: 1.0.1
  values:
    image:
      repository: tenstartups/ser2sock
      tag: armhf
      imagePullPolicy: Always
    timezone: "America/New York"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: usb
              operator: In
              values:
              - alarmdecoder
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 50Mi
        cpu: 15m
      limits:
        memory: 250Mi
