---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'regexp:^(v[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: nzbget
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbget
    version: 2.0.7
  values:
    image:
      repository: linuxserver/nzbget
      tag: v21.0-ls28
    service:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.153
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    timezone: "America/New_York"
    persistence:
      downloads:
        enabled: true
        existingClaim: nfs-media-pvc-10g
        subPath: Downloads
      config:
        enabled: true
        storageClass: "nfs-client"
        size: 30Gi
  valueFileSecrets:
  - name: "nzbget-helm-values"
