---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(v[0-9]+\.[0-9]+-r[0-9]+-ls.*)$
    # fluxcd.io/tag.chart-image: 'regexp:^(v[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 4.0.0
  values:
    image:
      repository: linuxserver/nzbget
      tag: v21.1-r2311-ls8
    service:
      type: LoadBalancer
      loadBalancerIP: 10.0.6.52
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    persistence:
      downloads:
        enabled: false
      extraMounts:
      - name: media
        claimName: nfs-media-pvc
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 30Gi
    podAnnotations:
      backup.velero.io/backup-volumes: config
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 400Mi
  valueFileSecrets:
  - name: "nzbget-helm-values"
