---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-red-test
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+-12-minimal)$'
spec:
  releaseName: node-red-test
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: node-red
    version: 2.0.1
  values:
    image:
      repository: nodered/node-red
      tag: 1.1.1-12-minimal
    persistence:
      enabled: true
      storageClass: "nfs-client"
    tolerations:
    - key: "arm"
      operator: "Exists"
    flows: "flows.json"
    ingress:
      enabled: false
    podAnnotations:
      backup.velero.io/backup-volumes: data
    timezone: "America/New_York"
    enableProjects: true
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi

