---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~0.
spec:
  releaseName: nginx-ingress
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.24.3
  values:
    controller:
      # image:
      #   repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      #   tag: "0.25.1"
      replicaCount: 2
      service:
        loadBalancerIP: 10.2.0.150
        externalTrafficPolicy: Local
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
        prometheusRule:
          enabled: false
      # tolerations:
      # - key: "arm"
      #   operator: "Exists"
      extraArgs:
        default-ssl-certificate: "kube-system/acme-crt-secret"
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
