---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  chart:
    git: https://github.com/munnerz/kube-plex
    ref: master
    path: charts/kube-plex
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.19.1.2645-ccb6eb67e
    podAnnotations:
      backup.velero.io/backup-volumes: config
    kubePlex:
      enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    service:
      type: LoadBalancer
      loadBalancerIP: 10.0.6.53
    persistence:
      transcode:
        enabled: true
        claimName: nfs-data-pvc
        subPath: plex
      data:
        enabled: true
        claimName: nfs-media-pvc
      config:
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: 21Gi
    resources:
      limits:
        gpu.intel.com/i915: 1
        memory: 4900Mi
      requests:
        cpu: 35m
        memory: 1500Mi
  valueFileSecrets:
  - name: "plex-helm-values"
