---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.0.3
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.20.2.3402-0fec14d92
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts: [plex.eviljungle.com]
      tls:
      - hosts:
        - plex.eviljungle.com
    timezone: "America/New_York"
    plexUid: 1001
    plexGid: 1001
    serviceTCP:
      type: LoadBalancer
      loadBalancerIP: 10.0.6.53
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: plex
    serviceUDP:
      type: LoadBalancer
      loadBalancerIP: 10.0.6.53
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: plex
    persistence:
      transcode:
        enabled: true
        claimName: nfs-data-pvc
        subPath: plex
      data:
        enabled: true
        claimName: nfs-media-pvc
      config:
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: 21Gi
    resources:
      limits:
        gpu.intel.com/i915: 1
        memory: 4900Mi
      requests:
        cpu: 35m
        memory: 1500Mi
  valueFileSecrets:
  - name: "plex-helm-values"
