apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth-jeff
  namespace: kube-system
spec:
  encryptedData:
    auth: AgA3Y67HVfOB9o/L01AlulwGIYOznxLWlJsV7QftZTUR9NzQXQBeTSLKgr0UZ8wdOIivlrEndcuKk5DUTr34JduKpRBVo//8QiwB1LinuFl+5AZRHepHZObHjNE9uHeZArcJqR32gs2WQ9H6AW0XtC/kZPsiNdYjV8wi62LQ1kWjg/Yn7+HYOblWYby1A6GsBEj/AYLctFhdG9vKFe10CPMsoqGl3M6Bv34psYTrH1I0ehe/f+OPzh3A0nKGk7YkibDf90sBxwTOc0lnJ+6By25bGpj5GwPZQZVIik+sEfxGu5wA/4r9AHzRxcWEUeYEJYHKdp4qOcSHNljzJCQM1+GqK7JzTdpchNNO/cBUvh3842fkEKtiHMaz7Syf/tCBPbVIai+Gx55KfLDS7lPL1pkNCWdkE4kgo3lb+gq30j1PgLBE7DWvgmLS0CfD8MONaxxZztcQAT1rzXHhTgXNPd3Z0mB8bt3TBTCZXm1XnCCtE39Xa7Sp84Tepu0jHvaHfKam9x7BpISBWF5TilUzxav16kLzgHPEQXsxSNRS32wHQxCmBF64LXDL/MVAy/K+8LFRH7+g7NA3kqoBzEivcYuEuNTYMtIkbTQ8CTzSU8GyRzTFrmjYVecS69MIu46aiPOOqtjcp8nI0ihbp3VXwK0lQm6qbc3LgZlru93IvKes2+jH6+L1tr/tbuPV0F4Ln0PQ1cfvYvV8+88m+0r3z8Uaf/c2t1+ayTyR/m40bkQ2/Omnr4LQAk049Ok=

