apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth-jeff
  namespace: logs
spec:
  encryptedData:
    auth: AgBxUSuD4l2M/C0io7rFyEveYZ7Fj50jqrJE0jtZbLp5oWolNZcyHNqxFJgV0byqlpomu2rkProvSYJ5hYJFhC3XmpoTbm+tTk5Lf40yTa7Kf9kWy0tRA2XPaj0Jajpyt3GR7j4hKChgpxF1F056FhIUyDahMFQleCSolkCm+OPuk2f48Enz6Fd/UzOyb0riVMpOT8kXrWgscTfCXoD/nSyfNV/xsqI7dzXI1LaZ6jjwOxhzsLWAgapgEse4P8CAh1uY0McfVMkLTHv0iRVjwpxq0i+lNMm6lZKVfuVfEX/YMY2II5WWHMG9be46+fmcdblHz7jubb4W+bXA+jI0iMtUf4OKOZ+bp7/8ZL88fN6OIcaaCqDiSauYybT6qg6ia4iHE1uJe0Fi3fFjJODeWH6ViCllG7Dnbq19rga9FtTe0VllBXlkAUVbNNr9mzqdybRolvN182mFyFk5Bqzq9iYm+drnRGlxC097sOK0XfqYtKbG+StROdiFWtCGofXO+sru2sggywsNFufrcZhiU0SYCJh0jUZhJyoFUpslAw1/YiXQdAJOAwnJNJKzr4EcB5oi+FHzpIo1Q54JxQxpnZqvyQLjWegf2yOnzsDQBVfjO0ZAyoSAaTZIB4WXqn9tfjOZsDvl5ySd8ZDxD7D2eFGcfLM5NmNtcOD28KoCP7Zpnot8+jqRBZFc/CYBfEUYC0MT71i47ujK8ds+KlaQzvA8OW83qaMOBFJ2IxJkO4GHk2B/Y9I6U63Cyrg=

