apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: deluge-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgATDg1LdRtrEiTbL4H0hmyxsOYhYB6fAX8OwrGTdCTnjjqVL7j3WnpLZdTZXeFjbnU6ZmW75FsbPgIuwkJYmKVBGxpBaOrRvIMkYQzTy6RGBGcJ3rO9xoaX71in81fOzqNAmjYQyIyJgpFHvPS8j98G99QDgUMlMa9X06GSnaZIbH8CKdf2j9Sl4MnNnRuYq4N8HCWp44NYw45s8t4bj7VgKlYqcf//CzwS7xei1vCeqMepc7AAX8z/6iJeE4qKiYtEvW4S/AzN1DEYTTDZCgMM8YlzxuhDviLuF0ARdcaHKdzijYNTBoxi6dG83WbaVyuP5kILw+nXqrm1MULJcdQsuDxYXvY2a2sqvyGpOnHG+8t89q+KFIXbSRKqwMs+Eh95PHucLERUs6qaScIw+z5TGIhfouMi36SnHd7GLU9QX5G33j3D+CEpvOE+FyWEu40dL3TmSwJu8hRYtCAs3Tmmdd5k9Qy8WNmAo5LBmTEOWCAWnwdacyAlBCQPavhrla8WRnHBwUxCKkAdQJsDxK/2PpSNEKf15zxmD8rAv8KjZsESBzFeiZ2WvNbvqPyRdgBaJeM0STqYqN2EZiPaxbcKM1EfGHowop1UVK+J7w38JeGBY4NSrf58k2uqskAGS1Lq6JOUVye/E6YOnFTrlFwxoYtyVHDn6v1jaDnj6QwlTZBLToB/mhBLxgwpWuf5P+1ZOepoxxGd34BGKH0TEKFSoej7Lc8pUSEHhOwSuzt8OZmg3e1iwkdBfQ==

