apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCZHDI3Aoigp/MUQ3LOPmLw+zxePfUcJZQkzr5e7TQ9V1x66008G6S6wrAmou24HfQA3KhumWxxY+APWuQSapmuisF/mysQTo/8glOgXWHUgjDd0jkwLCNBT4pZyKoQTMtHTawFI5tK2sxY27JxwCIg7sZQEZlwtzjYddFRTHSWJDcLr1szARjgC5VA+l3eTb7gGH0HpuHSyw5HUBg5T6jGcsSrg/YtAs11+LrZ+i0y+MgAZ98dk2t5VfIJctOT9tfVeNSi0Ce32z7w7+8Fnq0oJ+BdnlQcQGvLG5NQl4J1GQYFG/GD6cFp809r+R9n/jcC/Tp3oP/bS3XrkmdL+dYwJO8xMgvhJ+IxKdATSCNSC6GRYxzx+iJNw1lpx0elE2WYFUksvM7wd7pLR7t8re0c+JDvh2bOldvrQqSriT24ZzmjvJdivxCcZg/GigaKTXNI2TzmVzINRWT2BgH+WT8C3fB30wMpI7tj08xji1tlng+m7PIN1QRSl86HhYz6Lg86cPSkzRWhxgnDhz5j2K6pKZ2v/OiWucQ0t5euoghxN/PnrPfsqv4uIhxqYy07qAvNQk8VTJCUDUD3WXQopammUysN7s3VK4lNsNbi7Od0/2rXKk6Wz73K8eq4P3LW2+CyuNetPDeacYk2TMFpFO/IDrpd0untbaOo5sUPzsJANHvj0zK2bGK0HS9tpBohh8gjwuFPljXSNkkFepjnCCgNSs2/2m7kg4JyhUj7mMY7qqZpf01IpdW58gtX9IqHqbVGPHff2XPDDAhHCSXJDLyJFZH8uAJmxwqojQo+kw==

