apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hass-postgresql-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgARWGRpwUVKUk4LoPaTaVjEDzjIt21NOplYj5YXDVL5BSlTSa1ZiMqgN/vFrbVoIR/S4QP+EUCZeKZk8pfv9mxOvQz0+DV3QtWsbXlbu7fuoQjuKe/2mnPOB5UWNh5pNFY98hruMKLD9CVhUZb4lCwdgamOQ4UhHHccZ66vEQZzfghPbmxo5qA8mIhLkJaGakJlKKopww3UpxRpZZ2bzYuRrdWFFjKVcVYZUitvNqyWfE1mx14sFIEonmQgoMIWMbGT0jE4zwVdeRGKCXLDDnjTC6eTwgllvduYi8QGOgoZyiV5ZduP5T5+JQGi0Xiy3NJUjTF06d/K2AH4Y1kqFIcstDocSR5KL5Uk0QW8DhSEmfYFbN2v657Tt46Fzw6jaw/mg42yiMBxmLHpuqbzjByC8dLbOvAAgRLqzTXA5RUXk1a2p8wcaPNTB6/fxht8+UCnsKcwAu7NaFvdT43nY/vkjfnz+77+udj3utWxq1YtQArGo4PtMmpXJnI7lJgtAizqi+TDr96A/OLnBPsfB/RMhrc+ACS8LTjleZQippDC/eiUiJ0tC1EF+wJkdwVfOYrR5DoB7qqMfDikfkaEtRqN3iwf4X/a8TV9FzKpVV5Gy401JgfkU/TXGsjTwSS7xaJajcpGzfPMh68xBcYGq/ct3gb/RfJ0lGdI+vPIcN2fKSx7SgoOk/mJg4Noah/akE4s2s6voDh0QP6PCC2UOwOhrJ/Pud3fb0Q7F2+mxHE=

