apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hass-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB+ayeP6yDxVAftItQnZ8jpvG1P0Zay2MaHeD5DNmgNrLOVW4JSIIvv/+YzDoxJTLVYccaLzPXc9GxaM/fpgFTmBAfdZ6JF74lPbm7GxAsyA7y5rBSvNEOq+mQ7/UtMASq7f6v/t9trp1oic97cYHfbJyleoVhAdPb2Pm1yJ1quo5mEk7Xq/TxkjWP3NFBTGjyBB77LCrkYP044MiOoyWzE+9gZiGxzRBvqQnOwbl3OL82OS+/vhonF5Mp9tMtCkURxGt5MM/4mvOREMgpJzOcNxMOvYQnM5lqSuzDjLap+ZaVAtWU7VfV3HDQwfNWY8vkYc1IcOeFmcmiM5BqZMkO+w3VCDDhyLxhKl0HGfS7rR/FhAlGpkpxA70EggoNpJUP8QHuTyYbuD/LiOHSbZsa/FysyYJxMxO0I6vAcg5EjCtAObY1z1U0xSRceGY+URGaZQiURLmIdSTk+YN/BmooTwA5+ei3g2ofyGGbbOFTTjmqiz8UvaJEntM5y06/Yih5ipxXO5uEVakLA5JQ9sFdBCiKjF2Qf/Ru7XqsHo/hoyZkV4qG1QQG+VGEdgjUzOVzGu8T5lm6nzlsXX6fRJHEqLZosAaCMO5nt3QHNxXuwIQUnD1aOWnzs1zw7TLG6uNYtxrWeoCuqkE/GURLBhzuAwf5MV4uvtQ+3TgBtHQXaOhsHhHGlv2gzqZI+k27q6r1KS+PNWJ2C74pvdTaqCq87L3G+Yd3rpqviRBslE4UnVw38WG5IrNbW+3Qn6+6nRrKPrwfpXISfIL68lkLkOaNE5o739BVjjFCgAUTR8LTKdei4VN74pGICFEm2U8PVrQ0slSPXcDHXPsGkqpgtQ+3sSRAAlZTUjgwVu5yRBuSDD9ZVHU1Y5h0g0p/6wARdK+YgTBW6fWbiDU85IMobsLuqGhnVqLURC3Pt0UT5DgZfWqA2qbUoNl7Osa5ztx7+iVMaAXub/LQf/OZLoF19vHKzlUaWxBdBRbitmulm8DcjaHgR7Q==

