apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBLJ/OoxJnBoKcjwdnJhx/qQTEjwEhKydBLsKLUzcDxP+uiDSPeccWObVOm92dYC1XYNcday85YHIRGz9n0Fd0RkH/KcTQNghLLOCU5YUsxTX4YL+s96ggvKjCghjFow/D3DlhVj0rltoTg0NxEaCwVQkwV7kZmZ1yg0+t2pHqEe8WrhrwYY0a0yU9GGcMuG1cAs9ajCe9ZKSjn7Yu/gX8WuqZZ57f1UcAiqnxpG0ZW1ZdXW/+wO4AHwqYtPqxesn6Of6NUxcm80ogix5JRpgYnL3yS7I3lsydq5Z6+Laa49rcy7AzHLgphD5x1Ny01w3ydXtEbPP0rKJvWNUUvENLiG3nWceKINOf81+YueNDqQRLy9ne3udhQRg7dhk8j45SSemGnL3ShhHO6IWUhv3jwTZf8n1hqErFxRRFhTYhpqUj79exIR9hKY2353i0uVMEJsgRg9cCOEooVXZa/eXmNjjM0YeWk78eG3Xd5Ggwj5TKuVo3+mPE2g37i9BKnnpr23YZQETvzZjDj+PaE9Wn2N+UcydLagArwXosWIcC6VRp1JpZ3NGu6h12X8Kr6IBmE5dXhFFDrYjQ0nb4mMXoBifd+xLTAqWrmYbrVX1L+le/Y/XIEglk0bszmqsZpGFpZhNbnE8Ex5eFrloQ2TDs31F/hgzZHy33ouq8H7A7TuBdkntJcBfDQQ4gmfJ9QtgbRrTM7fyWvtjKInrc1rSVNCsNktCm3npp0rJBRRg==

