apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAjBuGsYiIXrOiP+jRz+Uj8KE9N+CwQy/TIq9exe0uFeHX5qB+HJiPoGOeKbZ9lSLI92VMFA8jzAK6jxPRr4KAmm24OepXp+bQ+70CpJta5ovr9brGnvHB0ttnj2H8bQTmGwH9SvsW3xSV7+mpKfJEoYIWwwPQFxnNVYnaz3zE0LE3S9kuMsFzKTboR7WekYo3DyAUho9lIgv64xaivL5Vg73bPRL4FMCET8v8aRsf02fM8cPyuRiUkNYhmZQICk6tu//eLGoj2medJf3iyetK8WT6qOpkET1wzbwaVEdyNkvCW5UoDYFFU2HXpkwZMSLhziPjIXsnvoZeBYR4zVaMr3WvN3axb93Q6oHtzR+w4EwBFgueEf/zpiSekwuvJdaquiHpg/xgtK2qNg4EvLzX2awgNc02UZAOgvBNV3z4PrdA7760FqA/f+R6+McS8OrdO3bsgSOzA5wYdrEjWFQnwaBeBV1s5yN3/UR0ZNu88y69SNZY6Y8kwZFNlXMhzQp7ZYOhJl9KMBSf5pkL/pIKOePIdaMn91idtFZnPH56adAnwW33EGJMtkT8BGVBnCICcAwKuvnaM1W4v1047kBBpmvNeD4LuqNI/k0vGnvbGx3nMfXQ46CnZPovNuiTOI6CbJw4nE+pgEwaqMp2tAg1lN42tFmbOdS7mpbv7lHMBbBBkA/d2CYK2jt7oORgOuyqM/iP0ZyLXbZPj0HqMzHNqkUx9jZBrEOEOsGhrAw==

