apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAyYAKkFovMU7lAVeg+FfXGXl+Q8G3koMQQAyHhgjbj8IcFNSd8lF86+XM4z5lzJpIFw54JEU9u42bohqv3aqsd3ZN4+fiEU9ShBHfy/5pXKwggEAYfj8MjNIHRnXb45/30gCAAnkd4y/ZbnkoI6SBY7j0ejyFEExthZAB3+Zrncc5L7lXdWR6YLBH6oFPKqXHQiCOlBCHbp8F6HoPoIaTObSOCod8Rb4Fo+YGWnL+aPSfYP7bU/ZW8BvKk3jmhz/kW/B1SUQCdvVvT4PrI3KGXqWUc2RVEpccpi2bgur4o8AzQYA0gYQzUg9HeD9xDQOadGVXDKWlv8ZmpurW3iPdSDrENUNNJ65QGHN4FtYN4n9O5s2z3fM7K2tnr7dETAaqMLL1PXFrcj8eRu1JFEtc3v9IkIetyHCOUZ3PZC516CjqLV1Xwlx39kUl5z0r6OZY9JS+0hHkz3aJTMAWGydbsAgtrx1Z3Hu/OIl2sLmFuFqlsE14FfMTsbY0duquaLknidyUvEKkwoi3t6iC8ZokVCagm/fTE+0LZGgp3PMumdlbuR0HUUBWzd7SCRWM6m6nKy3ttM3YPT5m80nXDjFXDwQxlIYrrR2p9qw6br96qzDYcJD0J9PHxfna+f86XaHCFBIJiNKxhR1kS9xdecuzmJMrqE1ivNcX3OtRglUWF8/PTt53mc0jO6YaUBCZE2WL/exutsQSJwXSOtFTQ1DGRSLe9TsK9UfaBkxfDSg==

