apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAS5fsi7T+heMs+YsSccvbLSph35MqH69uKyO87YqXudY6QHNLMxnh6uOI5ZnLxdvpD0DEktrzAUfoD2IurHdan7lho1KnAJ3GSWinZRRU9veAdvt2gG5yTrW+k/tgr08Mf7mld3NwySTs30zpsF7OmF4LQl+z7MMwmtl5XkcA0juUzJuAyWzWUloPCxHeGQ1mSS6d9R+UXCJpuxEZfUY4DtaYPdMBZEztMFSKZt8n1dfIrdu15Z+dp+MYLpGp0JlsY1gCnWlrJZ8V03WVKcHLGKogk9m/H2NO9xaOxdXciveZXDYpri1MJCz6Dd2Oyjuqx0r/q/Su+9D8B7wpiEPnCPcRL8ZDILyy/fu6CKwgGwUfP/vf00b+0zWgWlhL5KsPzuIWbPJOe6sS/s9Oi3C+hfsVZ2w7FlT5lbE88FPS/NURLY8r19j7VwQWsgfsYTXbjQqhBStihRpyoe76MRyH7w/6wLCLtOP61yAGGzI5Hto1ZZXynj5Ylh+7BShbkGiMcPEt/TFvv5VOiysx18N7/rPz1GGJgq3IJdtx+rR88WlVJjyucYx/UiDtJHmHN9dA5xJTtHDoF4U9LkgXpF+Wz8ppc+Tt523yu7fGGNc8xQn/GppWaVDmgAeiQjeDIf3a3PKeBHOKfSbWE1aRTLgK4HaDumDMu8yRnltsLUIRVAswVPqJr8nMWSqmjeIfVPYk+bxMAp2fFbXt3Dx0U38PRZv4sLWay6Cir5A1xkgdk

