apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBiqP21Ghza6v07ZZKe/pLUskaesLuTh3AKoagYFuQsCAx9b+UF0JpwbJBdFt2IPnk2VxUCvMr44nAb2ojjghuga517vz5RgEQ9tljMqr3sUwwIU3fZBfAtv8CWBoW1Uu1H61UwjGwhewTf0rBceIWrrxfEXGJIntPfJ/f5WHAcvWjokqdOvnJeDYP7Y1Z8osL6C88az6QQ/y51+XRhkHu+FeftKOW2y7bli/1xBfmJE2nFp4pZtjI+rF5U0ajQqsVT/0XkycDdEMNgo2S2kj6MdCpy53dSeOYCZE5FHpismCVXj3g4gKkMz0N0fAwdL2ZMlfm5Xq0zMFc9ab3Wj2ZraLk/6uudF39DyQwSBH1sVoGVn0IWjC30n/3swY0w7VbGc8CNB5SJ313oswW2GuT3noRFW9fl7Py4qULIq8L60YXICZBEjGmqgnRSddNhwqrhRSgzwu9HQjh/os6Ufz6zSjncv6eGmWaQ/xcqabm31NqryijSmDYsv1E8xfsHf7NRf2eznRBJdN/SU8E64rDtcTFMBSZm6yXG8/mDSOUiHa4Qbjoc5AZoZSjXZ7bK0dGJ53kraXMHDS0amsVF5XHdDlqr0brWRl4ai60bAlWZGHzOHOuMpvxo0tCXY1Tw+4M9A9+TnzLeQNd4Lbkyg6rxPVmGFJcUJy8X3t1vTKFodyNBz8bvFgeUUkMxGGH+8egGPdih0OuZ/4i/Khg/JNeyRAlPss4uR/FABE12+kyB91tiJHrRSwfL+CaRFh3HuVSoGJA8KxwPo1dep/uRR9Xa8CxsdNRBW6HatM7fIMDRNLDNcP8n4+DIVFzWLJZhVdSJyQF9PXINGxbyi/o=

