apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAfMWPeH9cLBBRyd4shEEPOcmdSLMgKWNF1KkSA98O95w+skGrBIQIn2HRH9HwzAh5gkWSKRoVK5BB0y6B9ozkmKqKBBTNppTzUZVLHhqT7mfA8SIrE2bJMCxabZcuteqc3+ajR1T1it1qBEen5fUo6Z9UYKabxa4SvEGg7GoEjlunI+AMgVcktAYDLOhOobBKVvOt5ncgD/ymvHJcJ/epwUrT91nonp8QQoOx+/v183+zwnhSAYl42I8SxlHpwOkL55AvgzeQPkGgSYuORsHs4EaybYkZwF4vkSCJx0BVThFi21czpdJZt1UgEXF+pxWWvR9MeUCKCYSf0rlySxPjAECsW7UvnuxnJrxyBKphRPJgw4WXEwq+ETSKtJWOL/Ce5YdCOrqCyI7zPj3iSncJozFpxoca2Oekk3kVVyaInciexxD8hw8KzFzSx0OKbBQJVOns7x8YLXuTe1IPklj7Dslf9jytNhmntXeqeCmIJadCParCxWW6Q3p74R1GgDUNvbRFSQmIIISlkesipY4TVj8/6KeEKt4QayebjaLH+0gMVKu+Q/0w8xOTKQdusa9sO7curxjj/6ZkDpZguxc2caXZB5xqtVgtBvIZA/OPl9CcmW2/xVYBBYvt6aUvz/YMRhsVJBjXEFgiW4fyOdaytbQ7vXzwDuf1p4Sz3LqCLWVuAqXrJJFLNg0mMWYv8s6wuVlYj7Pqe69vOKq/4zdmpoP7nQbI43LPMCsOV8VV15U3Q9nIO+PBthIX5plhJ9xd+VVfeI34v7JN3ykzGiEx/HxvYxMOScxJ9yfI9o6a1UeYztFD9ODyV5581GxItv8WBOzT7DGFhnlLXoZw=

