apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAbMJ0vz4pMQqV7rIUqdS9iTW7zjEBWdW6Hn9u3G84zc1pVSmMNg9+Erz/UdnCBeVlhAc+IbD5OIDIwCmcGXl8zAZK+1tVts9FvV96laC5wikIb82RqPe1uEzQZzQKtzfVfkqTKP8JIiSWrnwVUp27GlBOLZBPHHZ4OfySiWdxfU12DeN/KI27rq/RxlDaPoF2v9jFB6j9O7kUYKE13+0vcIO1l9LtPQQrYFglAIEq2WXjSQRVnzjzXTklUGVpbOcKjhyYCHXcU2oL24WI+PNmvF20OOp8fDO8AIEzbRaDGK+2hdY+Ep8ogJ9YAGtIaaIqhnNqCnrBo597JH1T6hXwz0O2VjZide7Xv3Iq3HB9XHmkFjjy8dZDd2ft3bZKdfXjMr35I/P3likGFlBHn6skoM3sdmrDTfXDhzRD3hcYrfQZZaSjlOqH9rtQdJHuEaDBHmXJ51Tcg3Nh6HvyNIHnkaT7bqMJXHcoG5EEYaXcnz/YO61wiihxMkh0KeTai3akcBV1m1wevMNj5z0h7z9pHuz2UUcAr64pHvRbQQe0XjjE3g+LHoroOfKQGz7OfIriacV+IUpEvJPuYAUefQ9jK7vzlh673XC9e6Ri9QDxYxnnWgbWy7Lz8vnZ4UwKdeVNZtXUbdAXVPrwpnRmt9BElx0Y8iS251UOkUaBFG/cmsGHhvsTdSUTyqKW0LLks50QbPdYf4jCp53cTefcxzogBOveA6OGuq+1lv/pw/bXyyBgu81FDBmROd1NwIakJ5pa2rSjvcy2EQOkX34YQCyUlTHNv9/jcIw5mWNTgSgu01F9hRxMHEgf/A85vv36/PfdaUUWdIT3ftH8FFBw=

