apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBkwRw70fM/LbVlOavvyHUdGMIxKXidf76WcRcyVwPuKonZ43cWTB1t8ZuU9m1kbYmf1m/1oS2xRLQhc2SZJ4N0Tf/Z8iwaAxiyZyzdeuASTdz//77IZkkV5sTzl5XNMvLcBUvh3A6Z1WEO/ARkCRbzSSU+6HmBDQtcDGy4NDeUPhZ17zcfBCEGo/NmVtvQMbZebWtKQfwIOyBTo7COzd5XTrw3KGE85y/1lqnmCLRyI8MPOt0DhqkhSQZlT5/eEMODHvPMoNUp7j++/lckHqZCNo5aMcuSKwKbr+ESLEteA4vjGXxRVdlT1lCijILp9NH5OrG/WdNdoQwiV1nkU4ZYAadOzmHjMiA+uXOVuVugAEBqPtHbu36MyUBZOQA87/dbw1hN4nlMUPKQrK5E8ntis/RNrzrDiqgw04rgoBO6w9qr9+EhQpp96P2yeFD6F0gu6spHbqM5j1KMwRHn5aI/cg0ahdLWex1/TvJzZ3Ozpx5c4OpbXSr4LUpDgv4r6FV+JNh8mEpkC2C5h9jA2JRvQps3X5LZd2eENfJwPCjrfLZfy2NYHuDagnE30OPg6aWJ2G8v4YUyEWv1tMQRZ0nC7Su+IibUHGVVa0iZXh9aY0+Jt1uL6TK/LOlvLGoGtgtvKMyMt1ae/o6dIDkwOkVNd0WR32OZDjaVEwzwOJMK4ktRYCN5bKS/+pzVAd6JvRN13WGk0rvXw5GRIdnrjL4TWJwYAthzTVu+YvDjMBL4NFKEfQo27dVnw/j8smT1W7/VoTXoJrNOykEkXzJPg/p6Bx3IfgkcZGyWG/1OE0UFCvjc2rrvH+ah6ZP4u8YNM1o77iDNGDfCy38N130=

