apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgCnhAJKaU8EyW72Aj/xGPmMJP9xUFY9WbVCOqi0oN19zw8jUaY4VwQwasIkQHeXcA8aiZIBGDHnL6NK/EXhPQqUPJ5p3mdrvwCuFvyaoZp0DOmADJl0O8u5L7sHLvBph7ltXamyTWSOyIo5n7ZGsaK9cuQsdOLTZ3k3IWlIbnckdNH89K6CC/Upk+N8jDuui5AUHeuMkzj01W2LPeKH0aaEZUFz4O9dPDNvbeQUIBP+WmPMgvB/SSknTpKneatPl+T9i5rjLldh8/kXb+mKErHTv9rk2kTTSqlVW7YCeGAmIN1+DWOkV17V+kwraDyqawQoTV73/dRd6Z8QGfkrDfHChQaZUEUutxadZqIO9E8chErQeBVJdS8CuMlHhSmMIDIcakda0VOwW/plwJ0dSY4zuJWjhnhrzkN/6v3LeZpHN9n3g5+PtYWFFFl35ztFkFkIyMr0QynbOAAjwzGgOiIXfSAtJr+DAo0IiJoPjGq4uIe+P+NmQRyuWdQsrCYaLZ4gF4Um34x38x6FpmtGbiBNKRRJhanQO7JvIRuunEjCMP16eIAfVj4nVfMNgQbldpo2mEyvlTvB6yifbpiSZcFM5q5i27w4jQbUZ5eADU2g1kOXCtjCkjRwof3wo+N0tGiStJ4auT2WeDj+i52TZoQp9J8b82obE+i/4kam6NiBm2ks7Hb/+myZTnFFSFWVnSz6meZ69K/pEDYDHclUWY1W9AKWzjRZiGAoMqmmcd3+lCk0htC/Lvg9BaeOxl0PSZMwBVde6IPFb46FmxsJPkuWTB4jPqmZUUSJ9I0mONa0GLYFbQNNDpKtneo7rVeCkN/JX5KBdRFFc9+xMJc=

