apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgCJuGaxUokhu3twko/WgvEC46A+6xqYAJePvd1Xml1OfSlksEFZlmf0WcUH/UYojs3iKXgcRhUrRTubRJgN9MuMpA4AAG7mR86xzOM0OH9/lE4lctt3mRmEmKezyKVVOCeoUV5eShzKCz6HHBCCq7I7lAu4Mcmg9+8L+gnlkIzTWCBOGV/xtfEcxuYKDnsRaz50Br1aZoXhKjkjNP0EllYoK4nID5/bVhPP8LCROg3yn58HuwHo7rRyEZqhIQXyDk6jPF7mZCSmtJtaL0ULyEZPWLTOOUIiAp921DdLt+kZ6IURqZxt5hxQvk40RIgvE0wVAeOoBxhw3QmEAEpnx2qFASiPlGlSsYaWKifDicPN0g7ULW27d9ZjyUrA1d2Ep+0CpCYYnC6U4DDw6U99BqPlWACOEeVKxRinZJlj+jCHT4P7vKfNnbtA4/fCBcT/vw/lV0AU/8zF1eVi6G5Kt/++qFWDCrcRS5k4LqUd2hlx0I2852PTs+JcEG66qVlZq5Gi6+nlyLz0Pet/M7QmLJsczQzSpKrnFCZX78Pu0+1c1dW+fHK/OCdBJTaoaUGxVmEmItOpVxhQ6SUQx9Dzee6D4sBhfAijMtDAGgEZTaqqazCXw+a9P4Wu3DXxvYMwL0lZSTrBtrIfK5b8PSL4fFOTL4n7CdvnsUbtAsV2kAAodJwycxMBO9JCu4F8SkmLBzfYTE7o5eBU4M+bJWDobKxiBjTyzpD+eUUNLkczdszLhluEx8ru6/yt1o+VtYEzNa+2TN/7b8a0pkQNQGJAVR2L+ezLBrz6We9M3H3FNjzdk6vRApbbuGmVL2Nygscyz/Vd1EHjx8k5Pw/qHG8=

