apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAmpNXmwO45w10ryZeWzk0wd9lmjadWlCx5BbtvzvYDBIebkYBhOrmI73Z+u47XmG9RZDvx2BWkFyjwnTNtCChRMDlG5RDG+QZ5uOtXgOWoW4VzklOtJwL5KIjnBSnJtdpDmceqWp+7YUdQR3baDK1Qb2vR1bgcTcFY6vUIGe2YXxKMKko+PLMD8vSWWNVRUkSBWWQp1PGjVLjs9r/Q0Xm9jjSu3wwSHj0oMkSBVSx8qVyfEzS30X6rxWuPMXh8PTBQbDs3JlJgkMY1X8cBeDVe06DZTvlkTEgLQdLvI88qghz+FuRH2jogEVLEkvE6nhhPFgYrOcE6hUNeUymWq8a20Vay9a0wxe/IuYdMpVinyvQDMwt7Og18rJa9Efh5symstPVh9M9hS/H8HHaj5Om5nM7mryo+wef9H06UOVPbDVYKma0t7k+AZ3Uj2Op6QBQzPXJZ5YaY5K6nFER/CmI69GnA0tmhgft3FDL3iOor7BXugCCgrGBYHA0XvNi6mSDyrNSyy0YiNvIRzPIR17gWlCQkej+T8eYWnMEpoXrOW2MKgUVfzZuzYoZb8c2teEUQEXgYA9ywuvRGkx1rXMzc9em7mQEQX30h/UFReGFnOWCIes1XaU1svPEfCNd+NjYdX3pIfJy3DIqGfIjmYGG/rKvq0J7rVJDzkahn8QmHQDBmMAEtwG5yFGs1dnkuGv0mmb4FE2IFjDJtUHX97w+s8YFLP5hGQr4jkd0dCpi7bw4QM4dsSNgGHzY8GUv5iDVkFdosUPBIKQGaIXyL40dEQszlv9FdiVYpSeDsa6TjKz8emI3dA08RxwdGEZApgfCBfcxscASDAhlx2M9vjPXUyf7L1qouZiHzClNYtteJkg==

