apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgANj4CcKNn1XjzsajwvPpB06PiLphDP3Lpl6YJcRrHHPAJHHJ8RG58N9YF6o1I4H/jKXume1QAKr6nqfcxSw2BToiuPDvO9plDIUgLL50onFK2IOu8HPUWhQmrhAF96R97mBVMZDgzYag9vHr/5m2ha07BDxqb7YQJ6Xk3JMIS8oMIswZfjaeXFm3RCl21a5f5VGIiZBkO3s1eodktq4WEUdHqTiq83wwhcG+R+m9AReDIJaRd63H2ORJx2is8IjUMJFxuWbqc8+CbcYCAvEJrn72ErJtchGI6nD7+Skea5CUMy8XQfJN5jnu6Au19co30XA9LKivNQNJFo984j/q7iEJ3qnlHaEfSqG8Dpt1/bURq3kj2NDdDADOw93ihzHBPKBBiFuOiOrDggWeGVXiUulu++9rCAo5iyjMZS6o/O8Wu5FaCf473TknQ41xhxJrax649wqIg4JudQOOl7Lfl+sQxsX/VSA9AKpFDQiDcORkDG5uQP2Klxuw63SmeQ5KK9r0b3AbBjoy6m/pziI53K1dRiUflh2UOLvjCYsXt1CaX88/lWYOjmsdoWSmYciYkhe81PhFCm4jROTVCnFH+zCHOS9YzBeCxF/6pIXYoSuI1KEEq3xVrzj8H9n3SsgtmIGBVnAom0e9eYdXXu6cXILcyA72zbPZZQoVMGRRD4P00VwC4kyTRk2uI62Ce/o0YFBJxxpwMkYGdfOCz3ozl+ZTs0SadZyY8bBOJ+CRyOmb5oYYD1CHDH9x5zxGCB+FJIK0dEP5XvnsBMBYUugnkYmYGJBz94OmNw71szSOL6Maw4PKlRjdYdofM40QU7bZCaRugHNf7m6uigVnHmbvpCQ6mmmDzRcnGCFcJbJs8kkURtO+FF7yRJy4Yj8L5gOy0rHYEPFHr2HSEv+/1CRg==

