apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: node-red-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCFhm7ANF+ESTbeVF9AkGD7xpavIJ20lLEcRcQPv1LlHRUgE/2nER+KlJLIo0t7+J0YMWiagA7XLilF4N+pJNoAPA40S79RC/oxHGnZolEPfTZ/z+sa2LkivBwqTtfe8e1bB1UyVQ6u2PqHjJaQCBSeEM8xurUS+yM7mqtAQSqGWKN/HbiWdCePOHpsH5odhhQZ7piq3XE2J0BCj4dLpYYY6YCCKmHjPfOuW6hpCAylSs5ii4w3eeq5xuXjgQddRm9xdZslnraBIlR43jyO0UPrxSVdUyFNwShUixwXX4epLAiIsBlWd6PvQR9BNWfxsCO/SUCedbgRNL8a5qGSD76ekrNmwK1Fte1GP7jt0TG8HZ8+YT+ZHoVFe5h+fs/mLrcdLMuCMcUYtrB1stW3i3Lcf8hXnM50hLAf+aTf2AwU1hhVkVDxLQbUNBJtd/4VLd/Aew5hw5XBRpfZyOTRD32VwWjVZ6rSLHyxCi1tt89yErUB6BPigkA4K1KX5Y8lJPr4mAA6x1P8ZG4yURoTHYxoLBvVEh1+4z9m2QXSffjrpDsA8MPFLmfJ/F7psZlmSHg4XbzhhNWhwa3FUGMeAbUNk1AN0rmEI1HgMipFjZMOQJLulSnXCs70wYUGvwzpc3KTJqfVtEnsPY2Bhf78tmvN3K1+i79XLLN0Qdi+6SDyMIPRrG55msXbwdcooDC+NPoRYkvOiW3eIyrDlq3EvzGD7uXoBLYb9wH0YHTPda52XktDIPqeSnIlK+qf

