apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgByrLsGXDTRcJMMNHAWRYCTqBApJU9oHRjTXtcFKV542xl1NM6tRmVWDilIhTDdvk2b0eIRvhcP0wsx0/HbmptF1t+8+YoShNP1CkPsuAqRgSrPAtOMO9jPgKLx0AVOGGcTgxBcPzqhcy24guWwEbYrDCDnvVDBbf6xG2QBUNewdRaR1g/XjVg9/3D7MlGi6i9i9/RBfbhnEenw0V81rdvIiUEFubDm5fAfpHDfydWZ7hQLbDQ8ncs40QyIP6gJZppoGX0wHlWHfOAsK1pzymAF/F9q0Q/YnbcuyzhP4LcmMh04ewJgbTB1KqClvEwOP/BZvItXYS6FWNtn2W7frm9yr9zGriMVGInnfwWzf13ECX6+s64B+XEUZSNOn8E+WDztr2P2lRIu4POke1WuCr1r2rF9QvevcmqjybPOhRDhgnyF2Eqww0RAzpz4J27PAmSplcgil+Of65wdvPuHqjWN0T2YpLbeZNcmFZ5TY3l1R4GpGFw716s3jmsrRsnwA7POtEbAaLEJVg7SHAAkVaKlFqo8DVP0iu46poyFdUu438OKC4zXe/70SCOu11XjfnIDqcNX42SM8B+ZAtNSrKQvLsIEu+jwAoPlnZjoQ7RRUsPPqwLF/h1Lu5mNvqFxX3fDpsBsSFhrvFcaa2cmiMfLoGZIorrKoviDjCWcS1GYl6OZNBieSpJAz27HJRq18OYGg/e13UPAtu8zuz6Y2wCOS7KV9AZM4kZyQy7rtendznC1QgJj0x7vLyQAWvsXH6c0EPDkNSmi0ivkrK7uixI6Dq1xym3hEulj3Yw7WLpB

