apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAk0zRBpq2+1IyXpSZQgW+40BELO5+G6AALxLuah0P77eD0nuMLAaqh8N3/ZQHImwWuu7gl88Yzx8OVW8HsQXhkaEHUDHeJAXzFFiH/dtO5xGoOwqI36t+MmDZ8ur2pIrbReuy3ebexpD5BUtItruylMnIhp59euDbuGNJjLEq89STu0R9CZeGRb1ERJt6HCXdULOfXWgj4T+wOpdDT1FduNZO8CjkKIfxBpbBsAam+FHae4H0tlFJATQ8XZxa2P0Sa3d+mA1DZCM9PdYDtTjt3L9+MbveGCDbv1tHkJYVeqpqhd7m9qhQvoVnKZKItuyJgUVy9EpZHiSmxNhgb4WbHeEqjtgDH/XrcKRXI4NX5ifg7RiOs0awzencAXY4OFful9W47n4r6Dy0xj+Plaelcf+aNVpp6tL5nPGUDBbPGUAi9tWTKThuOLcy6g3pxF86bu+jmp+9xuliMZBFgyfxWjT+wjr24a4Q/URD4s/2IQ2w8QFdL+Nmvl/dxD80vtoXcOD4ZSv5166if87IL8iD+Y4xHQM5ObcTuS3ZJkvPeeoumwK3KImnLuDSAQdwKC4eVD3rPrDIDJ+I5ON6XQoFIZpE/5dBe8yn4eiP0lNf8pLNrtIF4zxOTalCBJzreNm7OCGv527ZheKPJiL0D4mKyfsPjmTIiPiVaoZ14p0Eovd43mYyh049h6GxxfQ8sIWvImbn0PqWKR/U5OLX759exFJMWtps6duiwN6Z6kgnwP7tZNmfJGjcYhIaIf2W4CMXL7sTPX9ydU9pmyCVJZiV8P8A7TVIt68dNY+F/1RdRBw==

