apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCg/lzLiU1P+0+JixKYkupZsTe1OMqvAiS9sRN0jkQCWwidZpQX9fhMCCvCazXqcARWKmsQIw4l7NhVQ9sLJkiOv4NLBZCOWz6DCLCv2tfU85LBgsPc6jNRridcDQECKWf0VqkgSRrqp9smUCCdDF64pRsoiWu0e1wTkV3pGmq0m98nGRFF3p87q/iES07KZF5+KXyLCdh13K3W68tQ9ItwcA03ZYjnBs/p6LT/Dx+YbcMwdHci4k68cKoDK6fUVICjvvqe5zRBNEU/DtnqZLo7i8dQLUJrLzUCXamXgbG8eSJmyel8HLR1ntU6PH5VI9MQA4ZeEqzgmw5/nhpOtDd9iLop4wG+h6M1YqJQ6/QH15/4/x5wpdeezsLHP45M+sHGp2HssgfcvXM6E9dTiwgsref7gcUs0RIBrTrHrDqtxdfn/wqFpG/6Q9yithORebK3FKUceVR45zV49ghi/Bcu30QmcFM8O7i5/zqXao9G8oj56h3BT53g3UT6pUrwP+tRiE1RnjaFInReCSekx2ZaBlD6+NMHayp2l+wt49se9GvZ4Orkjbvx8Gdt8HXKLE/+CuCupxUA1MV39tsHMhoJKZwaGDfw4QYscIXWpPWDFhVKsTAwFGCZcU8N0xYmWcbU1gjVicLTlruXAa30B+LnG0NqCEBUPsjQJb2s8+obMTBtES/XKB4zbfluSMP46OSd6fu6woQL46zc6KUXAH7VrLGI/c2UWFZ0lhJdILZW0cfgFYLpC6TvzRhNM7/bR90uS/lHASINa4fEVrIAZatAsq83xCiqtgk9yKUGlaBnqYPbZXNna5b0Izhewltac4YyQJh23VvtO9cduUpQuImA9x1WnACVKA80KcRV66//fiM=

