apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBzJl+9nK/Z3C+U8LbCSxHpGaiqu1GFog/RaLiIXW7XhwrBk7ewMHtKquLdTSj3Jblr2SDYD5e4L0vAL3YryF1acGDfcmQateDrYat0I4/hQs3ZKanKiSOvMVF/yKhxFfXVGMmqNh617obVXEe3pGKif0yU7v6zMu3z0Mx90EELhM/hS5qIiITTqhetZg+CgwA38eV2PAO7t6Vqgrp/b6P6M1h7P71Q3ComqVzg3HsBCYnHONs8FU3EtUjT0c5RvSZlg9J7BIkiGLIFEisH+E09JrpUiiT4mM+VGP9FwPMDe6nCqsWnkPga04JTwja/V6x/yeJ9uZz9EC7ltG38Iu8m3D8hsUHmANWlJZ7GYBWy0YCpeEZq4HVrK9VfuAF5Jr+DxMUo7lVV+FuO8dBBhfifap7rgB5tWlARA6Z1xWUfFfUJY9F7fNTTNh4zkZTUySUkdQpi/qf1MBvvvciwgmKzW2A3zTrtUyKorI4Ix1Wo4k8FnLi0PULWGYJOBqHRF32nKMw8HnBtRqAbhxfjqDh9bkUbRn1tBWtPzZxu26kPaoe9G/F8OZKXclxFS5nv8j5Cvz0uLiedzzlP66g8KZ46mv4kwoIbd1h5B0FW0cMQDOjQgj0WOfzRXNR0Xt7tlRcoICBUT2akb2mEB3iCIcGGZyRcOTTjNin64167Xa8IXQAtzNkzdQbFrUYfAtFwtgvVP5+Uy3bV5hZcXUgZBrgZI5BtsaxP9g2zhI6pb/ppQDCY8R0oIM3e+rWV37/ALqXcAJQCrbyF6LyAazjFm/0CtxOJwUHt45EYclcUERpS3dxCotCF2zSKS4FoEnxHERDr3JZS/HzuBov/zQmwz5D2mneRBv8RjW1Tif6HhA==

