apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBBiqPz2bxXiuvuK9T3v4goUsOiQPEXQr03FNjoefL36fKmbEe0e8uJlFXgshpduqBqdH0cfKhS4lJZCjXUBDJz00UG7/+uVjYmfYSNEWr1Jutgzu3K/4TFPkq6CHYdsa5MngOzDVAF5vq2DlIoraXcwxypEzUMedBmS+uhpv+FZnW8wBzbS1lZt7ibrVv3YY2fFf5V2D56ClhxTBBEweV2kJi9mz3DMYhxi9tz+Moo/ZnwyatJZSLzZTlBK6PuK+3V5kqcExpxYcTaJdD8LmT2iI7/5LV54EeAAREKGPfTTj+8bjPHgabJVFw8mj8QdPYGzFHcJZnB1SY8BxrnvRrOufE+fO9hlqEPHolgnUEFDR01BXVMS4t5LZqlwd3ZH7i4GDNtjEq+3OqOqGweDVIn4uT59LiPJUZK/nWfhIuLy3poudWjHXfKpYmbZTfZ93SAFiaSfmzhg9mNa94DZejR2ijx7VJV5GGSPMFyvIJQ87G1yMJweOBCTFF0LtCIxHE49I9jv3Bx8EW6WGSEDZgrZXZGIWsW0cr4c8/or+xDjVBlSK4B5uuJkVKGY/b8ZX/BipPIW5Rdj1OTuqzSRvQvkz+ROUdP1zmVHqDtMiY02yFsodsFAfDevn0r3SOQzDAls3zS9V948ID+iFYBTQ8HQ6T9zGD9VTtveXxgpGZQEZig+7yGuMDDXtu5w8llCXVOR6Rlzn/ItQx8UbN28lNhS4fnCjH/srbw9HyJucP5q9pqx5SQRgs0HyZmnLrckVntlv/B87uKvPlavPY71V1828Cw/65dzWUKA31EyZByazq5oD1vEen3uYQDsKE8lBWT5zdrcr/Nc90e5nM1wH1EVCvp1gufqprNfMigQGQbb8Oq

