apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCa2QY0JMwWCiQPwuXq7KXP5CaVf2i5KBD34hRzqPip5C+W6YsE75pdMZYw8Yg4iuiGAZNLInOJFJMXk2cdzNdR3c/m6Ld0QU0lafDnIIwplJL3m+gfDmw8gugsb4z1OvRb/+fiiDh5KOMm5eupCoMGBAvy9rLrxtTcK41StFFLa2PTCzAKthEFFkEgkUuHjM0blLx9xRQ8yvGSsWvrMzZUL6+aaBRXPmBAOvadWmqlW+x8Alsw+sH0CNJwQiv5SC9dOZb0PjwDVFsoBXyWWpoUWqq6jcZAN4gZ3UIBmWAP6kGGX/zmp4evNvYjY/Jty3zfz1YaF+gIdzCZ1o8aa8+SXw6l3ZN28cw005TTATQlYUzB8cfL/5YbksDke6L4WBnuaXCvK2YzE3E4DI55M1UE889ogj4/1anE5hnLN6cBy1IqCBZK5zhlBHj0IBoaZQykJV6VvRdEkmRq5NU7dJdTdLdFB0qWnvzxgqRxsd3zAMkOH/9B07VH2/jXS9t3cKM8oGTRE/Y+vw3vf+8Xe6PMdt0GTLt/1WZVTaA0uSmSkGP8ptR/bVLHweJnJ28cO02kP4ybu38hd1vE0POlOOyQDGWojVRANQEmRdYlOsOYb62ntlmRT9DkVcNWfGdLlXs3qO+zCzD1zokCrL1dboQ5TiO5vTnBTubVnuFT+lQuDS9SMvKiHzGMxS980tk/Tg2zmwpNlVlQoP9PCO+qxH4YBreftsEx3nHZKzuqed5mWxJSPmNmNQAJx9F/+7xarxFbh3n+3RmxanbOH0Y44j+H0M8tpFnq9zsCVO8xVAIKNgkD7L7j/RIgBBFfCiv63jEKdfMcVT2slYJfEOl0ig4xpDSohtT60M+reF+dKnOwsYM=

