apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBFvOtoVvbEI6KkbtwDhh2NcPmwnWEoHCFcBXRn0V8KGiZ5oNXOhcLSVjkfDJJ9r0OIPsCAEhJ3CO++5lCN1Qbixeg2ulWo53DNoU/eZd3Zn4H11bTwluU7vMzwfyGBINuMFNTHFJd0rNUYSQ3kYgVutZoPjk/su8zNVT0fbMgFBW2yxNlwQsJ05N3P7Vv6lqES5mSkrT3b8HAwMFWG4jh2ZPmKdUEVX1YXcIv5MTJqHDR+y0OcNfFPnaMqWc91JbgzsgH4Jw6fT2a1e4L5CtWOsZwEVnFV40IYXKZ7VaMc+UGAEzTZ8Ce6SngMiHCcA2mzV97pR5COb9jf3nd/6N5mJVx9tWbS4aNX492lBCcSWwv0HV7zi+lqmaO3hLr3GiS4+ljYQjmI//A3t76AnEz9cGxXovBnnz5VLYPrczQBOO93pACrl1iwydlFWncqOEz+/zogXy2uZ77I4cb2HrNbEoOm/Dj2a0oFw97JvyedMqZPbyaPDc7S4gfdKUEl8cQbYBtbyY9Nt2IpDjh3Y/GZYSVXzQhPduOR9NgLZGViE1SsZhpa9f8u0i4WZfG9F10dO/t9VbplkI9cSX/cge/BF6xU4ObSkRciOe5XKVs61lE4yqGJ97mDNbpZz+/mwcgiVYF5VIBtKjocHXr+ZruUvs4Jxx106fyj+lm5mOlp9UFOlJqNlfmlY/FcOFgnFotTTNLAat/rAgiwXTmNGSNG//+yiU04hio9H9PWaA/TNqL6tzVdVpqRplTj5y59ft8g02mSOpyKMPYDC7OHxu1Ey8OPZr9cY4aEPrWsTYjYH6KpSwXXtCus0gBbifesxGxH/0keShTA0tY3Lw5uHNQBz9JWGUqMG/X8oW3PwmfFNEI=

