apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBTAgCSV3ES93+6zawErcwtFF6mUth7LSyTUQPFcj+9Kni1bFes4o9YuQW2CLyihlU+TRRb74dsJqfl4R6PFfuKgqLIuWadyNNw3thPHbOkJ2P4qirE4gIMBbJtUPohwefxNplEwdSYK9zqvl2jmTsChrfmkndKn0be0RddehMU9GDG65mZHk3W4YyXasaZeoou7Q1Mb55IwXYxgt5a1EiQg+q6D3yQ1J4z00tUISIeOmuXpE52In7Ix7bDx5VF+JEDmC+dEfajzBwNVXL454r07+ezhzB9jejqI2a6CnFwJ5jb7atqEEnzx0muLw/DwtcbvPltBMTUdZJn3Lmc+xvDT5CbQ6vC8oViKbTxy5HJ9yN/fMLZPQfDjZpmFhY60Cg1DZ1HHOkQRVFp6w6byIGy3UQrlmtcw6p3Kn8c9ilP6WAXRXAyj69+4mC4k3WVaypAWscn9K90VtEFBlUOVOpxvZj8T5KFT0zg1Q6leMssI/D5tm6wk+W0FuT1Z7/b0gwjnowHbNqlKPLiC6qGa0sAFhAEEmOU0VEvGLeHngG62d2TFyXDQr1rd5TwexQW6+r6rUqbLotAYf7UynsDkEE7QNyxVlcHQKnloBpdHGarQGtB1Wb8HuOIzZozH03fRjXmLQRURR8Bzy0YFAm7eN3EMRS6Sex+IOgrmRHjPh7Fsst7+K99gMXJwP4c4tqcop5j+W8lYHqFC5poPzk1PfDKCQHtaRqX7u9g1ftGrSyyPYcG7cYHBo8uJu2nN6s4kKHS0w0sz3ArH3jqe8gZoJJmk+IBVKHMVj8Y9LcMtmUrczJTS+HlbgySRz2ZwxNrg9jVyWMJ

