apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rtorrent-flood-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBmU/Iz3PHE8hcWOP7F7Hj5cloGy4DKB0VQmo4SYQvIawNWIz2sGHuwqIpn6LY0CmHFfB6Yd8yYdJjxieV3uirpEnlj6FgQigWkyNiBHlLS8nX9j62cKxgbCIAHrknDKJd3WMo6zDSnOwIeqL/dZwntlqoCy12lWH12XOqCOA0QW3DU7rFZx8yVNeEPr15rw0BJL/rsFUlNOaL2C0dk2IL+xW1iyRVWEA0pWaBa7HTa2AoPnopM0BjoCbOZdoD+R5hmf1VDksTX55ysJrCTyYSywSk+aUOz0tM8JR/y70D1+4hHHkwgiUBgQgMFehw+z+cJB6AZBD/zplc1Nj+iLtUACQfNzERzJlNHfT5nuZawP2mt+UlvnoJOr5XE5Dl+/WHK9icNCUPAWtfIzRUjfV//Ww5kHo+H+69qByg+4VIkiHyL/SwxgKNDWf/z737GRO12T8TWTGZJzncmyaUUwL+MXTqslW4JXgHIffwAT/sh664U5JSGAfOW/CXTJxfxJqcOeyOF2Mch2Co4eGQBp338IG1Z2GodPeA10ntECBjg8RWABdoLtu5gjhk3BUCo/ZxW755Dhd0k9+RrN33UotgQANPSSDIAD89rVDuPd3MBz9BA5EVE1TFAeeOO6DlOdfns06r42irmHSV3zh5/4D1sE6M8fVDrLkNbxxHxr6XdJ8sdFrEpI/QekQqYbhoNck6nfcLW4T0KUbPt7MNWnM95MooKQ/ivqxWDijfGJRrnipsH/Kg0a6w9jfEEJqwhBn3F3xAGhcqTFg18+nM=

