apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rutorrent-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCgpNRT2ZohM0jtoIuv94js1HLXmLlZJJLGOqHNE01KpS5gTmYPG/zSIW7wk5NfYk0P7gWEK64QiGimwvhxddW8DQmhMUbqHpgAE0ntjIJxkZaNXgsheMz37vQhFg8xEsTmU3cA4wUGb93Zmj9iDvRn4MThv6DGfUbzcsD61AdkpnngHIcIQq4gmYVPg+XQC0OKg1rhrV1AkS7W6oJrHRbFPC615ULYhgKF1Duv0nusZIeSt8N2ACITKQgonuJNQFD69RmNEo4DvJVVkLpd7Q/h6Urb24bv8Smw5eC9NLBIc8Dvl23gywbPE04xvzMtt6w0zhJkJ1M8jYT/Nkzs4JaL3ohRNsC+jOK9cCpWa0pgkPNFg/oDMwQv/E5geF1Gs/q4GaqdSZwJk5EeGU0gO1DQjj2vwPMcdxW1pxYo2lDGKfGZ1QwpPxE42OwP348hGDbZSvdnbIS77kikNvz/ZK8ypzgrB7LgDRVmwPijWk7z4GE41z+hCAS++qxAHymmIEUklmuJ5lefoLGATFr127Fna/onlf+CgpiHicJ+02vpxauLF/wfi5cUm57RBf257Vkjig6PpDpoDECw7qJi4r2DEA71neLzQGFZbF5f8gtd3wAw4pDcvZAaFzTJz4WPBC7/ywnyQ0V0YcCLWTtYqk1tWK67PtUc+8lUclOpUrx2J8nqLj32A/ITfxwG1+Ywkn110bUtMud2/Y2IJPJKnTshdCudiaCC60AqtJF8GJiJ/dw1UuVJbmclxw3IlA==

