apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCECHvXar8HvTrZWpUbYVxxNhS6Y2Z4DYvIpcp9gNsYf5M9gvd8tMuyqvk7Pg0fzPg1z1DK5hMjVi0XARWV8QSRT1qP4Xl7A7n7XVueJmrFykfdlGTpEdkUB+Ptca9EYqLipnCudxqUWDE7+q1gpv6e9iZOhMdwHCY+WjI8C5641v9AhQBl0SA1zwtW6iI1VvMxjxfOnU/riONh8x7/CG6yH/3jtQ7pk72oKsNoxkhcZdhDrRPf+/2IYkG7q55/skeCIXa31/MMUK4WOzejxMEwd5ee1CwXtxhBlhAoMt979VW9AuAMcgt7E2EYtn7MyL7c5+I47EZALAKatWQUysEM1iuZ2anVjAc5DAc/SDAqKkUZuJeNp98GaiYQkswlnBzmOzq0EXaSeVdPSWnB2rFAs0lLkkAeHPPG2k09sQzKCLvnWd79fZy9VU9L0S+XrYoAAuz4+65ykcpATZ5hrOoUkrUpnlHuDtyMnLYVjr+/gDsM++3VM2Pp7jwNHXYgGlet510uV379NonLMx1SjwUIB3zduXsgX3ISnNO2W0IfMBiX/zJDXrNnLh0unfF8gDfxQtRRNmYdmBg33Mx8Y/wtsZDLAL7Pm2Kw7LxIcEa8/l+mI+M8xKuRYyA1KMuc+NgnTZYjbcsavcMHwCsE3eZSh7MuEvjaIJA7MqcDyjM/GxLh+KqVGhF91N5Gy9oKvyd6WGeuJ/hrewsjtZJa+P5PD/meRi2i/nY7Qi/UGQ9YXxFFSZLBRj4gDw==

