apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-test-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBwdqRdmydfArDkPc2g18drOJaGD20y77BiH4+lbFDBcl5+Td2orBsgyOWaaQNFzD7uqjE4WOBN+06C6S2zK3v/CYYk4BbfNXYVucR2Cg6LgmSfi0OHYGqhSylKaEeABSYdIlV/aMCa4VmnXiNi1X4Bh8BHWS6OFRm/y2Z8pkkT+sdYDw07yFuXXVgiW+CobT2vyj+05q/jjnnJ1BbvF/SfPXHPfWX495yKgz7Jb2C+Gl+erzXR28uMIOkUL6u09niAskVAWS9nT7UJbE9ioDGYKI8ta89yBZf7QQ2EnL0J/fAGrOdJfsejjybhSQFUoCBuf93/hRWYeJumadNsmWGCIANyXtVzOko0vxkwj2Dk2hRb562Lhy4HPM7MTyDqZXPgs0z67HfVqQXQNP+Vdksn/JSYYTZMMWdkyHcwYcpyTF8Bt6mypVoeDAba3wSJocpMZfXKiz/wq1Y0uzUvzkalzOjjQ/22FQniBAZLryYr62os095wcUufPs0gnWDn0q4YC8ezEFzlf3Y/4TqcMuTCyAuzAZGva/BYzmEwPm+mSxMutyfZOJPU29k7h8+kklYmZVLt9fLjwvraDeRd3mTsC1LjiKcqI6DimeMwjbpBWnWT27U6ufC1QUrsTbN9QfYpfdFLVOphJwQV71dyFMkrvrwqA/Q1gYvZdG078ujGA/Vqg+rOq+FScLDkkhFXldOA17G3GAbC5KlYmt3Azl7B16ZDPwgV8v4yFAZ0GQWwnIa8q4w8zPZE0ZLVYfOT5GzHiZ7y/6HvsybdYH/m4qro0s334SYVOp4x1s3N5SNmQQ0XSxQvxusV7W0FotzVB8pM4qdP1dPHg+NSLzlaKF97eaMiIKfemznY4phtIGrbgaaF+4zNxyNFZWGrOfTUWu8LZp4jk41CMYf3ZZTKtLOWwaUPprDYupAFTWXDTk49akjQOlumMe3fYlVrtKr9JjUW8wFjJGRa4c2pbHjCjbZVKygUtoBQVHtWVHC/cRAzHLTEV2A=

