apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unifi-externaldb-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCAMBZZ3qFHF+ZcuLnsx952GgZTwYANdqXCbQcK8iHv+pY1XeqJ6YP6/rVNDKWkvU61mH3eYm0Wd+woUTl/sAbcnKn5wzwMhQntdNn8FMZLD3ILCDkLOdP6nfL6i+XaTcfxE0vPHmtw+xnbIrIM/vicCuCUYJzZxH86+gmVKIlfDr0YUvz60aDzYxFFKIUC6UykGbGJhzckjWpuA2XOKpNvPrFlpBpqxZ+mH0xeOj4dTBKyah+Z5y2FY75T7BGfuE806vUFHsQCB4FRmxAmSKKj/VOhM8YnPlstpSJnhuQohZUKRRYnA3mjP1DHgeTQc6kwcIuCDqqLKXL+AdXc31tsTXZ+VDlgDtdI2uFI/f9QRR9NiCZfikl4Hgg437bn+5LKc3m/QTrgUQcn+C3m04+YP2tU+BFPS5ofUa2QUyyhLIa4zrl39D6S+io2jJji+eCqG9do796pyVcXf+3m0AniK9nSRe60MpQwm0TlRhx44vo/7pmGu6mBwYmwhWKVEiWo+Vjse22co92evQS+ou/anmX5ssI4KptUsSoMTn7NMcQaNtZz/sx/zQ75YBL92y90wcPxTuzRJdKAueoXCNuOrHL3FcFb7YO3iCIazY1XGPvZbgEYyEldOnP8UKhPeRtMlvV5FdFPkD9hCB+U3cN4hgbQZGMCyqGMhaxC6FAXBgXWK5buJhZI6HFoddi4MgQk+5lQo+OgMIt7Ny59B/g7UK9cR57PSmW9fYIoYg==

