apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uptimerobot-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCFwSlNZgDtnS9G//wFpTneDSaFyf3k01FrsnGc0Xdp+FJjSu/o4sy5tIlM4II1Xo+yxUXOoxIcld1Lr20CvGkVQpRTinfwVEzY2tYg1ZY8dU/k5Hdh9XNPCtmg3mt7S9FOXvQ7fh2tqiAnjVNgPu2au4ReiEbIPlIgsB88apkW256zJpjaOQ5ejwsaCPNvohvcm7S6LM4d0xpq+w00fKU7Nl+hG67S51RKAroVzTI1NiWhgXWuBFBcjv4umdW3DMhzYmDe4LykOtJ7TGo11F2uNrV2pcidV+f0j2K9atEudITRHnx6frZG0Qc57ftLy5Oa/dlrugBIcDuBFDgzZyxWtS3bQUhwsqEZnBL+R0Pw6iOGg3eaKoEdBXsjkVGWTrmSm4innLwYAZGjp5cnRROObWAEeue+r8ACcO+mq13M34EZH1kAz1BKt5PM7xfIdrfhK302yPQtc/grOj1p2E9JihpCum4n0kR65rUpnJUTRtkkswe6q7U3QhpVIxAFu+pDsa+jWLFUuPLTePoZ7qM5guGVTc0MNuDbn6Ms5xS2FDHfBmYZsxZtQLOh4PftVDWMu6lEBRxDmj8esEl0rJCgEhUj3amigqjv7S7Zc6Bfej1S+dH0Yu/AC4Y5tTQJ8zGAbRrhFz5H+9Z3i9fo4QUaS9Lod+ruOhz63n/Q4ltpIcia0VavItJQTxPklMeJ/2BBFjl2OFMEa7A1MSZ5Ei3o3vFNndvJmiSxDID0N5fdpZ6ZMPzUXdv7qwCnUjFT683YWqkHemoD/Xoxf0KWO6u1i4ZC6xE=

