apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-values
  namespace: velero
spec:
  encryptedData:
    values.yaml: AgCQnbefFehXbWR9+88jKA2Gxabs2XOWfmyL9tOsFywl8gljKPk8KXhtR0vf67Lgyl5YBOLF1Scaklfp8I2dEWV+Wo3HJmJIkVHtrMVMh8lXNkuM2FkvW4gCiD0S6V49MjQ6bay9KOCL/9WeCBpc08y5RuVfIZYwx7RTmcR9aPv/nF+4P5rlK/eKv1BBYg3wqKEaPycRNpitwW8dSEIMH3SSrqk9AJXhWdQwEsTq09EiJcAxTnwPgtTAaUsPdvVGfqjxnhLe9V5qpyoRNFdW7660bZRg3v9ch48Mh9nox+lJAFbHbYZHwrzaSEwauyJrvuMmwBNrBiysqIOVJ0VCvePade8/32hwsNZC+xSqHZs2US3QgfN3FTTyeeIwgxfqa439reOByZeklve7Zd/gydDMlCAtY/CIijsBgMREdQD+No/HSx9B5km5oxPXvs9kyBrYM7y1DwwnBFlUc3fWqw59AasfVq8RF/Qn7BhtODcCA6ecHt2clFxIe8ht4xiC8YIs13zcS6RmJ+kYUnLHhrOx10wsOAYHCArHJIptCZ/mzl7IJE41BGd7iEBFy+djeXoyjB/RXYgXhJWsM29dvL2PCFMz97VwAc0JGux09+CXR8gtVrx2oVKefWlLaEoDCh6P4w6i1OdXFctnhUUbzKIFodZUT2mHTLGVM4vPZxI6I8VFcZUxIID+Rec2JbXbkM2N0t3BVYUelZQbvOZXaTYKA7KTsOHVFVeoPWeQe4H4A4GMbsOtczRGlA5U0UG7S+KUqNc3G3KByWKiEl01LRAaO3sRyeku484Z2NhViVUCzLb9ycI/svzCg78kTLMBzZS9rheHwjGhHB9Ifs03QVjOO/vjEVhJSpw8cr2Ptw8nSRZLHACQ8q+9qjHKDSZ5fidJ5A1VFsNp9GyzdNj9/vvy//lsKDZ/Kb/NV5yAlMCIExy5yRSU5KB6axdpf8N99bI=

