---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: regex:v4.
spec:
  releaseName: qbittorrent
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: qbittorrent
    version: 6.4.0
  values:
    controllerType: deployment
    image:
      repository: k8sathome/qbittorrent
      tag: v4.2.5
    env:
      TZ: "America/New_York"
    service:
      additionalServices:
      - enabled: true
        nameSuffix: bittorrent
        type: LoadBalancer
        loadBalancerIP: 10.0.6.57
        port:
          port: 50413
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
      hosts:
      - host: qb.eviljungle.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "qb.eviljungle.com"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: "5Gi"
    additionalVolumeMounts:
    - name: media
      mountPath: "/data"
    additionalVolumes:
    - name: media
      persistentVolumeClaim:
        claimName: nfs-media-downloads-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 2000Mi
