---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^([0-9]+\.[0-9]+\.[0-9]+\..*-ls.*)$'
spec:
  releaseName: qbittorrent
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: qbittorrent
    version: 0.0.1
  values:
    image:
      repository: linuxserver/qbittorrent
      tag: 4.1.8.99201910202234-6729-cb31684ubuntu18.04.1-ls47
    uid: 1001
    gid: 1001
    guiService:
      type: ClusterIP
      # port: 8080
    btService:
      type: LoadBalancer
      # port: 49161
      loadBalancerIP: 10.2.0.155
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: nfs-client
      data:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 250Mi
        cpu: 35m
      limits:
        memory: 1000Mi
  valueFileSecrets:
  - name: "qbittorrent-helm-values"
