---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^([0-9]+\.[0-9]+\.[0-9]+\..*-ls.*)$'
spec:
  releaseName: qbittorrent
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: qbittorrent
    version: 3.0.0
  values:
    image:
      repository: linuxserver/qbittorrent
      tag: 14.2.0.99201912180418-6819-118af03ubuntu18.04.1-ls60
    uid: 1001
    gid: 1001
    guiService:
      type: ClusterIP
      # port: 8080
    btService:
      type: LoadBalancer
      port: 6881
      loadBalancerIP: 10.2.0.155
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        size: 5Gi
        storageClass: nfs-client
      downloads:
        enabled: false
      extraMounts:
        - name: media
          claimName: nfs-media-pvc
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 3000Mi
  valueFileSecrets:
  - name: "qbittorrent-helm-values"
