apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: metallb
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: 0.1.24
  values:
    configInline:
      peers:
      - peer-address: 10.0.7.1
        peer-asn: 64512
        my-asn: 64512
      address-pools:
      - name: bgp
        protocol: bgp
        addresses:
        -  10.0.6.0/24
        avoid-buggy-ips: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.9.3
      tolerations:
      - key: "arm"
        operator: "Exists"
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.9.3
      tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "armhf"
        operator: "Exists"
